Repository dnd-side-project/dnd-7th-6-frontend, pull requests merged in 2022-08, with the labels that each got.

#55 [#20] 추천 메인 페이지 구현 & android UI 버그 fix
  package.json
  src/SwiperData.ts
  src/components/Banner/Banner.styles.tsx
  src/components/Banner/index.tsx
  src/components/DefaultScrollView/DefaultScrollView.tsx
  src/components/FrameRecommendOrganism/FrameRecommendOrganism.styles.tsx
  src/components/FrameRecommendOrganism/FrameRecommendOrganism.tsx
  src/components/PoseRecommendOrganism/PoseRecommendOrganism.styles.tsx
  src/components/PoseRecommendOrganism/PoseRecommendOrganism.tsx
  src/components/RecommendSituationPoseOrganism/RecommendSituationPoseOrganism.styles.tsx
  src/components/RecommendSituationPoseOrganism/RecommendSituationPoseOrganism.tsx
  src/components/RecommendSituationPoseOrganism/index.tsx
  src/components/SituationPoseRecommendSwiper/SituationPoseRecommendSwiper.styles.tsx
  src/components/SituationPoseRecommendSwiper/SituationPoseRecommendSwiper.tsx
  src/components/SituationPoseRecommendSwiper/index.tsx
  src/components/SquareCard/SquareCard.styles.tsx
  src/components/utils/Pressables/PressableIcons.tsx
  src/icons/SearchIcon.tsx
  src/screens/RecommendScreen/RecommendScreen.header.tsx
  src/screens/RecommendScreen/RecommendScreen.tsx
  src/utils/valueOfPlatform.ts
  yarn.lock
Labels: feature ✨

#57 [0.0.1] release
  src/components/RecommendDetailDiffOrganism/RecommendDetailDiffOrganism.styles.tsx
  src/components/SituationPoseRecommendSwiper/SituationPoseRecommendSwiper.styles.tsx
Labels: release 🎉

#68 [#61] NaverMap 추가 & ios podfile 수정
  ios/Podfile
  ios/Podfile.lock
  ios/hot6.xcodeproj/project.pbxproj
  src/components/NaverMap/NaverMap.styles.tsx
  src/components/NaverMap/NaverMap.tsx
  src/components/NaverMap/index.tsx
Labels: feature ✨, config 🛠

#69 [#60] Map 화면 Bottom Sheet 추가
  babel.config.js
  package.json
  src/components/MapBottomSheetOrganism/MapBottomSheetOrganism.styles.tsx
  src/components/MapBottomSheetOrganism/MapBottomSheetOrganism.tsx
  src/components/MapBottomSheetOrganism/index.tsx
  yarn.lock
Labels: feature ✨

#71 [#62] 주변 포토부스 마커 찍는 API 추가 & MapOrganism 부분 추가
  ios/hot6/Info.plist
  package.json
  src/apis/getPhotoBoothLocation.ts
  src/apis/getPost.ts
  src/assets/images/marker.png
  src/components/MapNaverMapOrganism/MapNaverMapOrganism.styles.tsx
  src/components/MapNaverMapOrganism/MapNaverMapOrganism.tsx
  src/components/MapNaverMapOrganism/index.tsx
  src/components/MapRefreshSearchPressable/MapRefreshSearchPressable.styles.tsx
  src/components/MapRefreshSearchPressable/MapRefreshSearchPressable.tsx
  src/components/MapRefreshSearchPressable/index.tsx
  src/components/NaverMap/NaverMap.tsx
  src/hooks/requestLocationPermission.ts
  src/querys/useGetPhotoBoothLocation.ts
  src/screens/BoothScreen/BoothScreen.tsx
  src/types/index.d.ts
  src/utils/getApiServer.ts
  src/utils/getGeolocation.ts
  yarn.lock
Labels: feature ✨

#79 [#74] 부스 상세 페이지 상단 이미지 슬라이더 영역 구현
  src/BoothDetailData.ts
  src/components/BoothDetail/ImageSliderOrganism/ImageSliderOrganism.styles.tsx
  src/components/BoothDetail/ImageSliderOrganism/ImageSliderOrganism.tsx
  src/components/BoothDetail/ImageSliderOrganism/index.tsx
Labels: feature ✨, BoothDetail 📖

#81 [#76] 부스 상세 페이지 키워드 박스 영역 UI 구현
  src/components/BoothDetail/KeywordOrganism/KeywordOrganism.styles.tsx
  src/components/BoothDetail/KeywordOrganism/KeywordOrganism.tsx
  src/components/BoothDetail/KeywordOrganism/index.tsx
  src/components/utils/KeywordBox/KeywordBox.styles.tsx
  src/components/utils/KeywordBox/KeywordBox.tsx
  src/components/utils/KeywordBox/index.tsx
Labels: feature ✨, BoothDetail 📖

#82 [#77] 부스 상세 페이지 리뷰 영역 구현
  src/components/BoothDetail/ReviewOrganism/ReviewOrganism.styles.tsx
  src/components/BoothDetail/ReviewOrganism/ReviewOrganism.tsx
  src/components/BoothDetail/ReviewOrganism/index.tsx
  src/components/RecommendDetailContentsOrganism/RecommendDetailContentsOrganism.styles.tsx
  src/components/RecommendDetailContentsOrganism/RecommendDetailContentsOrganism.tsx
  src/components/utils/UserReviewView/UserReviewView.styles.tsx
  src/components/utils/UserReviewView/UserReviewView.tsx
  src/components/utils/UserReviewView/index.tsx
  src/types/index.d.ts
Labels: feature ✨, BoothDetail 📖

#72 [#58] 지도 스크린 바텀 시트 구현
  src/BoothSummaryData.ts
  src/components/BoothSummaryView/BoothSummaryView.styles.tsx
  src/components/BoothSummaryView/BoothSummaryView.tsx
  src/components/BoothSummaryView/index.tsx
  src/components/Chip/RoundChip.styles.tsx
  src/components/Chip/RoundChip.tsx
  src/components/MapBottomSheetOrganism/MapBottomSheetOrganism.tsx
  src/types/index.d.ts
  src/utils/toLocaleString.ts
Labels: feature ✨

#80 [#75] 부스 상세 페이지 설명 영역 구현
  src/components/BoothDetail/DescriptionOrganism/DescriptionOrganism.styles.tsx
  src/components/BoothDetail/DescriptionOrganism/DescriptionOrganism.tsx
  src/components/BoothDetail/DescriptionOrganism/index.tsx
Labels: feature ✨, BoothDetail 📖

#84 [#78] 부스 상세 페이지 후기 사진 영역 구현
  src/BoothDetailData.ts
  src/components/BoothDetail/GridPhotoOrganism/GridPhotoOrganism.styles.tsx
  src/components/BoothDetail/GridPhotoOrganism/GridPhotoOrganism.tsx
  src/components/BoothDetail/GridPhotoOrganism/index.tsx
Labels: feature ✨, BoothDetail 📖

#85 [#73] 부스 상세 스크린 구현
  App.tsx
  src/BoothDetailData.ts
  src/screens/BoothScreen/BoothDetailScreen.styles.tsx
  src/screens/BoothScreen/BoothDetailScreen.tsx
  src/screens/BoothScreen/index.tsx
  src/styles/GlobalStyle.ts
Labels: feature ✨, BoothDetail 📖

#83 [#64] MapSearchBar header 제작, 페이지 분리
  ios/Podfile.lock
  ios/hot6.xcodeproj/project.pbxproj
  src/components/MapNaverMapOrganism/MapNaverMapOrganism.styles.tsx
  src/components/MapNaverMapOrganism/MapNaverMapOrganism.tsx
  src/components/MapSearchBar/MapSearchBar.styles.tsx
  src/components/MapSearchBar/MapSearchBar.tsx
  src/components/MapSearchBar/index.tsx
  src/components/NaverMap/NaverMap.tsx
  src/screens/BoothScreen/BoothScreen.header.tsx
  src/screens/BoothScreen/BoothScreen.tsx
  src/screens/BoothScreen/BoothSearchScreen.tsx
  src/screens/BoothScreen/index.tsx
Labels: feature ✨

#88 [#fix] 부스 스크린 lint error 수정
  src/screens/BoothScreen/index.tsx
Labels: feature ✨, BoothDetail 📖

#89 [#65] Dismiss KeyboardAware View 추가
  ios/hot6.xcodeproj/project.pbxproj
  package.json
  src/components/MapSearchTextInput/MapSearchTextInput.styles.tsx
  src/components/MapSearchTextInput/MapSearchTextInput.tsx
  src/components/MapSearchTextInput/index.tsx
  src/components/utils/DismissKeyboardScrollView/DismissKeyboardScrollView.tsx
  src/components/utils/DismissKeyboardScrollView/index.tsx
  yarn.lock
Labels: feature ✨

#91 [#67] 검색창 구현 (미완)
  App.tsx
  src/components/MapSearchTextInput/MapSearchTextInput.styles.tsx
  src/components/MapSearchTextInput/MapSearchTextInput.tsx
  src/screens/BoothScreen/BoothScreen.header.tsx
  src/screens/BoothScreen/BoothScreen.tsx
  src/screens/BoothScreen/BoothSearchScreen.header.tsx
  src/screens/BoothScreen/BoothSearchScreen.tsx
Labels: feature ✨

#92 [#90] redux 추가
  App.tsx
  package.json
  src/redux/actions/MapAction.ts
  src/redux/reducers/mapReducer.ts
  src/redux/store.ts
  src/redux/types/MapActionType.ts
  src/types/index.d.ts
  yarn.lock
Labels: feature ✨

#94 [#93] 포스트 리스트 상세 스크린 구현
  src/components/Chip/OptionChip.styles.tsx
  src/components/Chip/OptionChip.tsx
  src/components/PostListDetail/CardListOrganism/CardListOrganism.styles.tsx
  src/components/PostListDetail/CardListOrganism/CardListOrganism.tsx
  src/components/PostListDetail/CardListOrganism/index.tsx
  src/components/PostListDetail/FilterOrganism/FilterOrganism.styles.tsx
  src/components/PostListDetail/FilterOrganism/FilterOrganism.tsx
  src/components/PostListDetail/FilterOrganism/index.tsx
  src/components/utils/Pressables/PressableIcons.tsx
  src/icons/BottomArrowIcon.tsx
  src/screens/RecommendScreen/PostListDetailScreen.header.tsx
  src/screens/RecommendScreen/PostListDetailScreen.tsx
  src/screens/RecommendScreen/index.tsx
Labels: feature ✨

#96 [#95] 커스텀 탭바 적용 및 redux 전역 상태 추가
  App.tsx
  src/components/RecommendDetail/ContentsOrganism/ContentsOrganism.tsx
  src/components/RecommendDetail/ContentsOrganism/index.tsx
  src/components/utils/TabBar/TabBar.styles.tsx
  src/components/utils/TabBar/TabBar.tsx
  src/components/utils/TabBar/index.tsx
  src/redux/actions/TabBarAction.ts
  src/redux/reducers/tabBarReducer.ts
  src/redux/store.ts
  src/redux/types/TabBarActionType.ts
  src/styles/Theme.ts
Labels: feature ✨

#97 [#95] 탭바 show & hide 애니메이션 추가 및 theme 변경 사항 반영
  .eslintrc.js
  src/components/PostListDetail/CardListOrganism/CardListOrganism.tsx
  src/components/utils/TabBar/TabBar.tsx
  src/components/utils/Text/SubHeadline.tsx
  src/styles/Theme.ts
Labels: feature ✨

#98 [#67] 지도 검색 화면 구현
  ios/hot6.xcodeproj/project.pbxproj
  src/apis/getSearchedLocation.ts
  src/components/MapLocationSearchList/MapLocationSearchList.styles.tsx
  src/components/MapLocationSearchList/MapLocationSearchList.tsx
  src/components/MapLocationSearchList/index.tsx
  src/components/MapNaverMapOrganism/MapNaverMapOrganism.tsx
  src/components/MapSearchList/MapSearchList.styles.tsx
  src/components/MapSearchList/MapSearchList.tsx
  src/components/MapSearchList/index.tsx
  src/components/MapSearchTextInput/MapSearchTextInput.styles.tsx
  src/components/MapSearchTextInput/MapSearchTextInput.tsx
  src/components/utils/Pressables/PressableIcons.tsx
  src/hooks/useDebounce.ts
  src/icons/DeleteIcon.tsx
  src/querys/useGetSearchedLocation.ts
  src/redux/actions/MapAction.ts
  src/redux/reducers/mapReducer.ts
  src/redux/types/MapActionType.ts
  src/screens/BoothScreen/BoothSearchScreen.header.tsx
  src/screens/BoothScreen/BoothSearchScreen.tsx
  src/types/index.d.ts
Labels: feature ✨

#104 [#103] 카카오 API키 숨김
  src/apis/getSearchedLocation.ts
Labels: bug

#101 [#100] 지도 화면과 BottomSheet UI 연동하기
  src/components/BoothSummaryView/BoothSummaryView.styles.tsx
  src/components/BoothSummaryView/BoothSummaryView.tsx
  src/components/MapBottomSheetOrganism/MapBottomSheetOrganism.styles.tsx
  src/components/MapBottomSheetOrganism/MapBottomSheetOrganism.tsx
  src/components/MapNaverMapOrganism/MapNaverMapOrganism.styles.tsx
  src/components/MapNaverMapOrganism/MapNaverMapOrganism.tsx
  src/components/MapSearchList/MapSearchList.tsx
  src/redux/actions/MapAction.ts
  src/redux/reducers/mapReducer.ts
  src/redux/types/MapActionType.ts
  src/screens/BoothScreen/BoothScreen.tsx
Labels: feature ✨

#108 [#99] 포스트 필터 바텀 시트 구현
  src/components/Chip/FilterChip.styles.tsx
  src/components/Chip/FilterChip.tsx
  src/components/Chip/OptionChip.styles.tsx
  src/components/Chip/OptionChip.tsx
  src/components/PostListDetail/CardListOrganism/CardListOrganism.styles.tsx
  src/components/PostListDetail/CardListOrganism/CardListOrganism.tsx
  src/components/PostListDetail/CardListOrganism/SortingListHeader.tsx
  src/components/PostListDetail/FilterOrganism/FilterOrganism.styles.tsx
  src/components/PostListDetail/FilterOrganism/FilterOrganism.tsx
  src/components/PostListDetail/FilterPages/BrandFilter/BrandFilter.styles.tsx
  src/components/PostListDetail/FilterPages/BrandFilter/BrandFilter.tsx
  src/components/PostListDetail/FilterPages/BrandFilter/index.tsx
  src/components/PostListDetail/FilterPages/FrameFilter/FrameFilter.tsx
  src/components/PostListDetail/FilterPages/FrameFilter/index.tsx
  src/components/PostListDetail/FilterPages/HeadcountFilter/HeadcountFilter.styles.tsx
  src/components/PostListDetail/FilterPages/HeadcountFilter/HeadcountFilter.tsx
  src/components/PostListDetail/FilterPages/HeadcountFilter/index.tsx
  src/components/PostListDetail/FilterPages/NestedFilterOrganism/NestedFilterOrganism.styles.tsx
  src/components/PostListDetail/FilterPages/NestedFilterOrganism/NestedFilterOrganism.tsx
  src/components/PostListDetail/FilterPages/NestedFilterOrganism/index.tsx
  src/components/PostListDetail/FilterPages/PoseFilter/PoseFilter.tsx
  src/components/PostListDetail/FilterPages/PoseFilter/index.tsx
  src/components/PostListDetail/FilterSheetBackdrop/FilterSheetBackdrop.styles.tsx
  src/components/PostListDetail/FilterSheetBackdrop/FilterSheetBackdrop.tsx
  src/components/PostListDetail/FilterSheetBackdrop/index.tsx
  src/components/PostListDetail/FilterSheetFooter/FilterSheetFooter.styles.tsx
  src/components/PostListDetail/FilterSheetFooter/FilterSheetFooter.tsx
  src/components/PostListDetail/FilterSheetFooter/index.tsx
  src/components/PostListDetail/FilterSheetNavigator/FilterSheetNavigator.styles.tsx
  src/components/PostListDetail/FilterSheetNavigator/FilterSheetNavigator.tsx
  src/components/PostListDetail/FilterSheetNavigator/index.tsx
  src/components/PostListDetail/FilterSheetOrganism/FilterSheetOrganism.tsx
  src/components/PostListDetail/FilterSheetOrganism/index.tsx
  src/components/utils/PressableIcon/PressableIcon.styles.tsx
  src/components/utils/PressableIcon/index.tsx
  src/components/utils/Pressables/PressableIcons.tsx
  src/components/utils/Pressables/PressableSubmit.styles.tsx
  src/components/utils/Pressables/PressableSubmit.tsx
  src/constants/filters.ts
  src/hooks/useFilteredItem.ts
  src/icons/BottomArrowIcon.tsx
  src/icons/CancelIcon.tsx
  src/icons/DotIcon.tsx
  src/icons/RefreshIcon.tsx
  src/redux/actions/PostAction.ts
  src/redux/reducers/postReducer.ts
  src/redux/store.ts
  src/redux/types/PostActionType.ts
  src/screens/RecommendScreen/PostListDetailScreen.header.tsx
  src/screens/RecommendScreen/PostListDetailScreen.tsx
  src/styles/Theme.ts
  src/utils/toggleTag.ts
Labels: feature ✨

#112 [#110] 포스트 작성 메인 페이지 구현
  src/components/PostWrite/AddPhotoOrganism/AddPhotoOrganism.styles.tsx
  src/components/PostWrite/AddPhotoOrganism/AddPhotoOrganism.tsx
  src/components/PostWrite/AddPhotoOrganism/index.tsx
  src/components/PostWrite/InputContentsOrganism/InputContentsOrganism.styles.tsx
  src/components/PostWrite/InputContentsOrganism/InputContentsOrganism.tsx
  src/components/PostWrite/InputContentsOrganism/index.tsx
  src/components/PostWrite/InputCustomTagOrganism/InputCustomTagOrganism.styles.tsx
  src/components/PostWrite/InputCustomTagOrganism/InputCustomTagOrganism.tsx
  src/components/PostWrite/InputCustomTagOrganism/index.tsx
  src/components/PostWrite/SelectTagOrganism/SelectTagOrganism.styles.tsx
  src/components/PostWrite/SelectTagOrganism/SelectTagOrganism.tsx
  src/components/PostWrite/SelectTagOrganism/index.tsx
  src/components/PostWrite/SubmitOrganism/SubmitOrganism.styles.tsx
  src/components/PostWrite/SubmitOrganism/SubmitOrganism.tsx
  src/components/PostWrite/SubmitOrganism/index.tsx
  src/components/ReviewImageOrganism/ReviewImageOrganism.styles.tsx
  src/components/ReviewImageOrganism/ReviewImageOrganism.tsx
  src/components/utils/Header/LeftBackHeader.styles.tsx
  src/components/utils/Header/LeftBackHeader.tsx
  src/components/utils/Pressables/PressableIcons.tsx
  src/components/utils/Pressables/PressableSubmit.styles.tsx
  src/components/utils/Pressables/PressableSubmit.tsx
  src/components/utils/TextField/TextField.styles.tsx
  src/components/utils/TextField/TextField.tsx
  src/components/utils/TextField/index.tsx
  src/icons/PlusIcon.tsx
  src/redux/actions/PostWriteAction.ts
  src/redux/reducers/postWriteReducer.ts
  src/redux/store.ts
  src/redux/types/PostWriteActionType.ts
  src/screens/RecommendScreen/PostWriteScreen/PostWriteMainScreen.tsx
  src/screens/RecommendScreen/PostWriteScreen/index.tsx
Labels: feature ✨

#113 [#109] 지도 페이지 재 구현(미완)
  android/app/build.gradle
  android/build.gradle
  ios/Podfile
  ios/hot6.xcodeproj/project.pbxproj
  src/apis/getPhotoBoothLocation.ts
  src/apis/getSearchedLocation.ts
  src/components/BoothSummaryView/BoothSummaryView.styles.tsx
  src/components/BoothSummaryView/BoothSummaryView.tsx
  src/components/MapBottomSheetOrganism/MapBottomSheetOrganism.styles.tsx
  src/components/MapBottomSheetOrganism/MapBottomSheetOrganism.tsx
  src/components/MapNaverMapOrganism/MapNaverMapOrganism.styles.tsx
  src/components/MapNaverMapOrganism/MapNaverMapOrganism.tsx
  src/components/NaverMap/NaverMap.tsx
  src/components/ReviewStarRating/ReviewStarRating.tsx
  src/components/utils/Pressables/PressableIcons.tsx
  src/icons/ColorStarIcon.tsx
  src/querys/useGetPhotoBoothLocation.ts
  src/types/index.d.ts
Labels: feature ✨

#116 [#114] import error fix
  src/components/utils/Pressables/PressableIcons.tsx
Labels: bug

#117 [#115] 포스트 리스트 상세 페이지 API 연동
  android/app/build.gradle
  android/settings.gradle
  package.json
  src/apis/getPosts.ts
  src/apis/getPostsByTag.ts
  src/apis/getTagForm.ts
  src/components/PostListDetail/CardListOrganism/CardListOrganism.styles.tsx
  src/components/PostListDetail/CardListOrganism/CardListOrganism.tsx
  src/components/PostListDetail/CardListOrganism/ListEmptyComponent.styles.tsx
  src/components/PostListDetail/CardListOrganism/ListEmptyComponent.tsx
  src/components/PostListDetail/FilterOrganism/FilterOrganism.styles.tsx
  src/components/PostListDetail/FilterOrganism/FilterOrganism.tsx
  src/components/PostListDetail/FilterPages/BrandFilter/BrandFilter.tsx
  src/components/PostListDetail/FilterPages/FrameFilter/FrameFilter.tsx
  src/components/PostListDetail/FilterPages/HeadcountFilter/HeadcountFilter.tsx
  src/components/PostListDetail/FilterPages/PoseFilter/PoseFilter.tsx
  src/components/PostListDetail/FilterSheetFooter/FilterSheetFooter.tsx
  src/components/Recommend/PoseOrganism/PoseOrganism.tsx
  src/hooks/useFilterTag.ts
  src/hooks/useFilteredItem.ts
  src/querys/useGetInfinitePosts.ts
  src/querys/useGetPostsByTag.ts
  src/querys/useGetTagForm.ts
  src/types/index.d.ts
  yarn.lock
Labels: feature ✨

#118 [#109] 부스 지도 페이지 재설계
  android/app/src/main/AndroidManifest.xml
  src/apis/getPhotoBoothFilter.ts
  src/assets/images/focusedMarker.png
  src/assets/images/marker.png
  src/components/BoothSummaryView/BoothSummaryView.styles.tsx
  src/components/BoothSummaryView/BoothSummaryView.tsx
  src/components/MapBottomSheetOrganism/MapBottomSheetOrganism.styles.tsx
  src/components/MapBottomSheetOrganism/MapBottomSheetOrganism.tsx
  src/components/MapFilterBrandChip/MapFilterBrandChip.styles..tsx
  src/components/MapFilterBrandChip/MapFilterBrandChip.tsx
  src/components/MapFilterBrandChip/index.tsx
  src/components/MapFilterChip/MapFilterChip.styles.tsx
  src/components/MapFilterChip/MapFilterChip.tsx
  src/components/MapFilterChip/index.tsx
  src/components/MapFilterOrganism/MapFilterOrganism.styles.tsx
  src/components/MapFilterOrganism/MapFilterOrganism.tsx
  src/components/MapFilterOrganism/index.tsx
  src/components/MapNaverMapOrganism/MapNaverMapOrganism.styles.tsx
  src/components/MapNaverMapOrganism/MapNaverMapOrganism.tsx
  src/components/NaverMap/NaverMap.styles.tsx
  src/components/NaverMap/NaverMap.tsx
  src/components/ReviewStarRating/ReviewStarRating.tsx
  src/components/utils/TabBar/TabBar.tsx
  src/icons/ColorStarIcon14.tsx
  src/icons/ColorStarIcon38.tsx
  src/icons/CrosshairIcon.tsx
  src/querys/useGetPhotoBoothFilter.ts
  src/redux/actions/MapAction.ts
  src/redux/reducers/mapReducer.ts
  src/redux/types/MapActionType.ts
  src/types/index.d.ts
Labels: feature ✨

#122 [#121] 안드로이드 특정 기기 ui 잘림 대응
  ios/Podfile.lock
  ios/hot6.xcodeproj/project.pbxproj
  src/components/MapBottomSheetOrganism/MapBottomSheetOrganism.tsx
  src/components/MapFilterBrandChip/MapFilterBrandChip.styles..tsx
  src/components/MapFilterOrganism/MapFilterOrganism.styles.tsx
  src/components/MapFilterOrganism/MapFilterOrganism.tsx
  src/components/NaverMap/NaverMap.tsx
Labels: bug

#123 [#109] 지도 focus 된 마커와 바텀 시트 오브젝트 연결
  ios/Podfile
  ios/Podfile.lock
  src/components/BoothSummaryView/BoothSummaryView.tsx
  src/components/MapBottomSheetOrganism/MapBottomSheetOrganism.tsx
  src/components/MapNaverMapOrganism/MapNaverMapOrganism.styles.tsx
  src/components/MapNaverMapOrganism/MapNaverMapOrganism.tsx
  src/components/NaverMap/NaverMap.tsx
  src/redux/actions/MapAction.ts
  src/redux/reducers/mapReducer.ts
  src/redux/types/MapActionType.ts
  src/types/index.d.ts
Labels: feature ✨

#130 [#129] Custom Alert 구현
  src/components/utils/Alert/Alert.styles.tsx
  src/components/utils/Alert/Alert.tsx
  src/components/utils/Alert/index.tsx
Labels: feature ✨

#125 [#124] 태그 TextInput 리덕스 및 로직 추가
  src/apis/getSearchedTag.ts
  src/components/Chip/TagInputChip.styles.tsx
  src/components/Chip/TagInputChip.tsx
  src/components/ReviewResultOrganism/ReviewResultOrganism.tsx
  src/components/ReviewSearchList/ReviewSearchList.styles.tsx
  src/components/ReviewSearchList/ReviewSearchList.tsx
  src/components/ReviewSearchList/index.tsx
  src/components/ReviewTagInput/ReviewTagInput.styles.tsx
  src/components/ReviewTagInput/ReviewTagInput.tsx
  src/components/ReviewTagInput/index.tsx
  src/components/ReviewTagOrganism/ReviewTagOrganism.styles.tsx
  src/components/ReviewTagOrganism/ReviewTagOrganism.tsx
  src/components/ReviewTagOrganism/index.tsx
  src/components/ReviewTagsSearchList/ReviewTagsSearchList.styles..tsx
  src/components/ReviewTagsSearchList/ReviewTagsSearchList.tsx
  src/components/ReviewTagsSearchList/index.tsx
  src/components/utils/Pressables/PressableIcons.tsx
  src/icons/CancelIconWhite.tsx
  src/querys/useGetSearchedTag.ts
  src/redux/actions/ReviewAction.ts
  src/redux/reducers/reviewReducer.ts
  src/redux/types/ReviewActionType.ts
  src/screens/BoothScreen/PostReviewScreen/BoothTagInputScreen.header.tsx
  src/screens/BoothScreen/PostReviewScreen/BoothTagInputScreen.tsx
  src/screens/BoothScreen/PostReviewScreen/index.tsx
  src/screens/BoothScreen/index.tsx
Labels: feature ✨

#136 [#133] 부스리뷰 작성 화면 ui 전면 수정
  src/components/ReviewBoothName/ReviewBoothName.styles.tsx
  src/components/ReviewBoothName/ReviewBoothName.tsx
  src/components/ReviewImageOrganism/ReviewImageOrganism.styles.tsx
  src/components/ReviewImageOrganism/ReviewImageOrganism.tsx
  src/components/ReviewRatingOrganism/ReviewRatingOrganism.styles.tsx
  src/components/ReviewRatingOrganism/ReviewRatingOrganism.tsx
  src/components/ReviewResultOrganism/ReviewResultOrganism.styles.tsx
  src/components/ReviewResultOrganism/ReviewResultOrganism.tsx
  src/icons/BlueHeartIcon.tsx
  src/icons/LocationIcon.tsx
  src/redux/actions/ReviewAction.ts
  src/redux/reducers/reviewReducer.ts
  src/redux/types/ReviewActionType.ts
  src/screens/BoothScreen/index.tsx
  src/utils/toggleTag.ts
Labels: feature ✨

#139 [#138] 리덕스 코드 오류 수정
  src/redux/actions/ReviewAction.ts
  src/redux/reducers/reviewReducer.ts
Labels: bug

#135 [#134] FeedCard Component 아이콘 수정
  src/components/Recommend/FeedCard/RecommendFeedCard.styles.tsx
  src/components/Recommend/FeedCard/RecommendFeedCard.tsx
  src/components/utils/Button/LikeButton/LikeButton.styles.tsx
  src/components/utils/Button/LikeButton/LikeButton.tsx
  src/components/utils/Button/LikeButton/index.tsx
  src/components/utils/Pressables/PressableIcons.tsx
  src/icons/LikeHeartIcon.tsx
Labels: feature ✨

#132 [#131] 리뷰 요약 재사용 컴포넌트 구현
  src/components/utils/ReviewSummary/ReviewSummary.styles.tsx
  src/components/utils/ReviewSummary/ReviewSummary.tsx
  src/components/utils/ReviewSummary/index.tsx
  src/components/utils/ReviewTagChip/ReviewTagChip.styles.tsx
  src/components/utils/ReviewTagChip/ReviewTagChip.tsx
  src/components/utils/ReviewTagChip/index.tsx
  src/components/utils/StarBox/StarBox.styles.tsx
  src/components/utils/StarBox/StarBox.tsx
  src/components/utils/StarBox/index.tsx
  src/icons/Heart18.tsx
  src/icons/StarIcon16.tsx
  src/screens/StorageScreen/StorageScreen.tsx
  src/types/index.d.ts
Labels: feature ✨

#145 [#143] 로그인 페이지 구현 및 Screen 구조 수정
  App.tsx
  AppInner.tsx
  src/components/Login/LoginHeader/LoginHeader.styles.tsx
  src/components/Login/LoginHeader/LoginHeader.tsx
  src/components/Login/LoginHeader/index.tsx
  src/components/Login/LoginOrganism/LoginOrganism.styles.tsx
  src/components/Login/LoginOrganism/LoginOrganism.tsx
  src/components/Login/LoginOrganism/index.tsx
  src/screens/LoginScreen/LoginScreen.tsx
  src/screens/LoginScreen/index.tsx
Labels: feature ✨

#147 [#143] 구글 로그인 연동
  ios/Podfile
  ios/Podfile.lock
  ios/hot6.xcodeproj/project.pbxproj
  ios/hot6/Info.plist
  package.json
  src/assets/images/googleImage.png
  src/assets/images/kakaoImage.png
  src/components/Login/LoginOrganism/LoginOrganism.styles.tsx
  src/components/Login/LoginOrganism/LoginOrganism.tsx
  yarn.lock
Labels: feature ✨

#148 [#144] 카카오 로그인 구현 (Android) 및 login api function 추가
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/values/strings.xml
  android/build.gradle
  package.json
  src/apis/kakaoLoginBridge.ts
  src/apis/login.ts
  src/redux/actions/UserAction.ts
  src/redux/reducers/userReducer.ts
  src/redux/types/UserActionType.ts
  yarn.lock
Labels: feature ✨

#149 [#144] 구글 로그인 안드로이드 설정
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/values/strings.xml
  android/build.gradle
Labels: config 🛠

#150 [#143] 구글 로그인 브릿지 추가 및 ios 카카오 로그인 설정
  ios/Podfile.lock
  ios/hot6.xcodeproj/project.pbxproj
  ios/hot6/AppDelegate.mm
  ios/hot6/Info.plist
  src/apis/googleLoginBridge.ts
  src/apis/kakaoLoginBridge.ts
  src/components/Login/LoginOrganism/LoginOrganism.tsx
Labels: feature ✨

#152 [#151] 소셜 로그인과 백엔드 서벼 연동
  App.tsx
  AppInner.tsx
  src/apis/getAccessToken.ts
  src/apis/getPhotoBoothLocation.ts
  src/apis/getUser.ts
  src/apis/getUserInfo.ts
  src/apis/googleLoginBridge.ts
  src/apis/login.ts
  src/components/Login/LoginOrganism/LoginOrganism.tsx
  src/components/utils/Interceptor/index.tsx
  src/redux/actions/UserAction.ts
  src/redux/reducers/userReducer.ts
  src/redux/store.ts
  src/redux/types/UserActionType.ts
Labels: feature ✨

#142 [#141] 부스 리뷰 부분 커스텀 헤더 구현
  src/components/BoothReview/BoothReviewHeader/BoothReviewHeader.styles.tsx
  src/components/BoothReview/BoothReviewHeader/BoothReviewHeader.tsx
  src/components/BoothReview/BoothReviewHeader/index.tsx
  src/components/BoothReview/ReviewImageOrganism/ReviewImageOrganism.styles.tsx
  src/components/BoothReview/ReviewImageOrganism/ReviewImageOrganism.tsx
  src/components/BoothReview/ReviewRatingOrganism/ReviewRatingOrganism.styles.tsx
  src/components/BoothReview/ReviewRatingOrganism/ReviewRatingOrganism.tsx
  src/components/BoothReview/ReviewResultOrganism/ReviewResultOrganism.styles.tsx
  src/components/utils/Alert/Alert.styles.tsx
  src/components/utils/TextField/TextField.styles.tsx
  src/screens/BoothScreen/PostReviewScreen/BoothImageReviewScreen.tsx
  src/screens/BoothScreen/PostReviewScreen/BoothResultReviewScreen.tsx
  src/screens/BoothScreen/PostReviewScreen/BoothReviewScreen.header.tsx
  src/screens/BoothScreen/PostReviewScreen/BoothStoreReviewScreen.tsx
  src/screens/BoothScreen/PostReviewScreen/BoothTagInputScreen.header.tsx
  src/screens/BoothScreen/PostReviewScreen/BoothTagInputScreen.tsx
  src/screens/BoothScreen/PostReviewScreen/index.tsx
Labels: feature ✨

#128 [#127] 찜 스크린 구현 (LineSlideView 구현)
  src/components/Storage/PhotoOrganism/PhotoOrganism.styles.tsx
  src/components/Storage/PhotoOrganism/PhotoOrganism.tsx
  src/components/Storage/PhotoOrganism/index.tsx
  src/components/Storage/StorageHeader/StorageHeader.styles.tsx
  src/components/Storage/StorageHeader/StorageHeader.tsx
  src/components/Storage/StorageHeader/index.tsx
  src/components/Storage/SwipeOrganism/SwipeOrganism.tsx
  src/components/Storage/SwipeOrganism/index.tsx
  src/components/utils/LineSlideView/LineSlideView.styles.tsx
  src/components/utils/LineSlideView/LineSlideView.tsx
  src/components/utils/LineSlideView/index.tsx
  src/screens/StorageScreen/StorageScreen.tsx
  src/screens/StorageScreen/index.tsx
Labels: feature ✨

#155 [#151] 기록 페이지 헤더 추가
  App.tsx
  AppInner.tsx
  src/components/Record/RecordHeader/RecordHeader.styles.tsx
  src/components/Record/RecordHeader/RecordHeader.tsx
  src/components/Record/RecordHeader/index.tsx
  src/components/Record/RecordOrganism/RecordOrganism.styles.tsx
  src/components/Record/RecordOrganism/RecordOrganism.tsx
  src/components/Record/RecordOrganism/index.tsx
  src/components/utils/Pressables/PressableIcons.tsx
  src/icons/RecordUploadIcon.tsx
  src/icons/SettingIcon.tsx
  src/screens/RecordScreen/RecordScreen.tsx
  src/screens/RecordScreen/SettingScreen.tsx
  src/screens/RecordScreen/index.tsx
Labels: feature ✨

#156 [#153] 로그인 로직 수정 및 ui 추가
  AppInner.tsx
  src/apis/getUser.ts
  src/components/Record/NickNameView/NickNameView.styles.tsx
  src/components/Record/NickNameView/NickNameView.tsx
  src/components/Record/NickNameView/index.tsx
  src/components/Record/RecordOrganism/RecordOrganism.styles.tsx
  src/components/Record/RecordOrganism/RecordOrganism.tsx
  src/components/utils/Interceptor/index.tsx
Labels: feature ✨

#160 [#157] ReviewSummary 기능 추가
  src/components/utils/DropdownMenu/DropdownMenu.styles.tsx
  src/components/utils/DropdownMenu/DropdownMenu.tsx
  src/components/utils/DropdownMenu/index.tsx
  src/components/utils/Pressables/PressableIcons.tsx
  src/components/utils/ReviewSummary/ReviewSummary.styles.tsx
  src/components/utils/ReviewSummary/ReviewSummary.tsx
  src/components/utils/ReviewTagChip/ReviewTagChip.tsx
  src/icons/MeetBallIcon.tsx
Labels: feature ✨

#158 [#153] 기록 페이지 Organism 제작 및 setting 페이지 추가
  AppInner.tsx
  src/PostListData.ts
  src/apis/getUserInfo.ts
  src/apis/getUserList.ts
  src/apis/googleLoginBridge.ts
  src/components/Login/LoginOrganism/LoginOrganism.tsx
  src/components/Record/NickNameTextInut/NickNameTextInput.styles.tsx
  src/components/Record/NickNameTextInut/NickNameTextInput.tsx
  src/components/Record/NickNameTextInut/index.tsx
  src/components/Record/NickNameView/NickNameView.styles.tsx
  src/components/Record/NickNameView/NickNameView.tsx
  src/components/Record/RecordHeader/RecordHeader.tsx
  src/components/Record/RecordOrganism/RecordOrganism.styles.tsx
  src/components/Record/RecordOrganism/RecordOrganism.tsx
  src/components/Setting/SettingOrganism/SettingOrganism.styles.tsx
  src/components/Setting/SettingOrganism/SettingOrganism.tsx
  src/components/Setting/SettingOrganism/index.tsx
  src/components/utils/LineSlideView/LineSlideView.tsx
  src/components/utils/NotLoginContainer/NotLoginContainer.styles.tsx
  src/components/utils/NotLoginContainer/NotLoginContainer.tsx
  src/components/utils/NotLoginContainer/index.tsx
  src/components/utils/StarBox/StarBox.tsx
  src/icons/EditIcon.tsx
  src/querys/useGetUserList.ts
  src/redux/actions/UserAction.ts
  src/screens/RecordScreen/SettingScreen.tsx
  src/screens/RecordScreen/SettingScreen/SettingScreen.tsx
  src/screens/RecordScreen/SettingScreen/index.tsx
  src/screens/RecordScreen/index.tsx
Labels: feature ✨

#161 [#120] 포스트 작성 커스텀 태그 구현
  src/components/Chip/TagInputChip.tsx
  src/components/PostWrite/DirectTagSummaryOrganism/DirectTagSummaryOrganism.tsx
  src/components/PostWrite/InputCustomTagOrganism/InputCustomTagOrganism.tsx
  src/components/SearchTagInput/TagInput/TagInput.tsx
  src/redux/actions/PostWriteAction.ts
  src/redux/reducers/postWriteReducer.ts
  src/redux/types/PostWriteActionType.ts
  src/screens/RecommendScreen/PostWriteScreen/AddPhotoScreen.tsx
  src/screens/RecommendScreen/PostWriteScreen/CustomTagScreen.tsx
Labels: feature ✨

#163 [#159] 추천 페이지 전면 수정
  src/TestData.ts
  src/assets/images/logoImage.png
  src/assets/images/reviewBanner.png
  src/components/PostListDetail/FilterSheetBackdrop/FilterSheetBackdrop.styles.tsx
  src/components/PostListDetail/FilterSheetBackdrop/FilterSheetBackdrop.tsx
  src/components/PostListDetail/FilterSheetOrganism/FilterSheetOrganism.tsx
  src/components/Recommend/AddPostButton/AddPostButton.styles.tsx
  src/components/Recommend/FeedCard/RecommendFeedCard.styles.tsx
  src/components/Recommend/FrameOrganism/FrameOrganism.styles.tsx
  src/components/Recommend/FrameOrganism/FrameOrganism.tsx
  src/components/Recommend/PoseOrganism/PoseOrganism.styles.tsx
  src/components/Recommend/PoseOrganism/PoseOrganism.tsx
  src/components/Recommend/PreviewSixCard/RecommendPreviewFourCard.styles.tsx
  src/components/Recommend/PreviewSixCard/RecommendPreviewFourCard.tsx
  src/components/Recommend/PreviewSixCard/index.tsx
  src/components/Recommend/RecommendCommonBanner/RecommendCommonBanner.styles.tsx
  src/components/Recommend/RecommendCommonBanner/RecommendCommonBanner.tsx
  src/components/Recommend/RecommendCommonBanner/index.tsx
  src/components/Recommend/RecommendHeader/RecommendHeader.styles.tsx
  src/components/Recommend/RecommendHeader/RecommendHeader.tsx
  src/components/Recommend/RecommendHeader/index.tsx
  src/components/Recommend/RecommendKeywordQuest/RecommendKeywordQuest.styles.tsx
  src/components/Recommend/RecommendKeywordQuest/RecommendKeywordQuest.tsx
  src/components/Recommend/RecommendKeywordQuest/index.tsx
  src/components/Recommend/ReviewBoothPressableBanner/ReviewBoothPressableBanner.styles.tsx
  src/components/Recommend/ReviewBoothPressableBanner/ReviewBoothPressableBanner.tsx
  src/components/Recommend/ReviewBoothPressableBanner/index.tsx
  src/components/Recommend/SituationPoseOrganism/RecommendSituationPoseOrganism.styles.tsx
  src/components/Recommend/SituationPoseOrganism/RecommendSituationPoseOrganism.tsx
  src/components/Recommend/SituationPoseOrganism/index.tsx
  src/components/RecommendDetail/DiffOrganism/DiffOrganism.tsx
  src/components/RecommendResult/RecommendResultOrganism/RecommendResultOrganism.styles.tsx
  src/components/RecommendResult/RecommendResultOrganism/RecommendResultOrganism.tsx
  src/components/RecommendResult/RecommendResultOrganism/index.tsx
  src/components/RecommendSearch/RecommendSearchHeader/RecommendSearchHeader.styles.tsx
  src/components/RecommendSearch/RecommendSearchHeader/RecommendSearchHeader.tsx
  src/components/RecommendSearch/RecommendSearchHeader/index.tsx
  src/components/RecommendSearch/RecommendSearchOrganism/RecommendSearchOrganism.styles.tsx
  src/components/RecommendSearch/RecommendSearchOrganism/RecommendSearchOrganism.tsx
  src/components/RecommendSearch/RecommendSearchOrganism/index.tsx
  src/components/RecommendSearch/ReviewSearchList/ReviewSearchList.styles.tsx
  src/components/RecommendSearch/ReviewSearchList/ReviewSearchList.tsx
  src/components/RecommendSearch/ReviewSearchList/index.tsx
  src/constants/filters.ts
  src/icons/SearchIcon.tsx
  src/redux/actions/PostAction.ts
  src/redux/actions/RecommendAction.ts
  src/redux/reducers/postReducer.ts
  src/redux/reducers/recommendReducer.ts
  src/redux/store.ts
  src/redux/types/PostActionType.ts
  src/redux/types/RecommendActionType.ts
  src/screens/RecommendScreen/KeywordSearchScreen/RecommendResultScreen.tsx
  src/screens/RecommendScreen/KeywordSearchScreen/RecommendSearchScreen.tsx
  src/screens/RecommendScreen/KeywordSearchScreen/index.tsx
  src/screens/RecommendScreen/RecommendScreen.header.tsx
  src/screens/RecommendScreen/RecommendScreen.tsx
  src/screens/RecommendScreen/index.tsx
Labels: feature ✨

#164 [#162] 부스 상세 스크린 최종 디자인 반영
  src/BoothDetailData.ts
  src/apis/getInfiniteReviews.ts
  src/apis/getPhotoBooth.ts
  src/apis/getReviewImages.ts
  src/components/BoothDetail/BoothConditionOrganism/BoothConditionOrganism.tsx
  src/components/BoothDetail/BoothConditionOrganism/index.tsx
  src/components/BoothDetail/BoothDetailNavigation/BoothDetailNavigation.styles.tsx
  src/components/BoothDetail/BoothDetailNavigation/BoothDetailNavigation.tsx
  src/components/BoothDetail/BoothDetailNavigation/index.tsx
  src/components/BoothDetail/DescriptionOrganism/DescriptionOrganism.styles.tsx
  src/components/BoothDetail/DescriptionOrganism/DescriptionOrganism.tsx
  src/components/BoothDetail/GridPhotoOrganism/GridPhotoOrganism.tsx
  src/components/BoothDetail/HeaderOrganism/HeaderOrganism.tsx
  src/components/BoothDetail/HeaderOrganism/index.tsx
  src/components/BoothDetail/ImageSliderOrganism/ImageSliderOrganism.styles.tsx
  src/components/BoothDetail/ImageSliderOrganism/ImageSliderOrganism.tsx
  src/components/BoothDetail/KeywordOrganism/KeywordOrganism.tsx
  src/components/BoothDetail/KeywordOrganism/index.tsx
  src/components/BoothDetail/KeywordTagSection/KeywordTagSection.styles.tsx
  src/components/BoothDetail/KeywordTagSection/KeywordTagSection.tsx
  src/components/BoothDetail/KeywordTagSection/index.tsx
  src/components/BoothDetail/OuterScrollView/OuterScrollView.styles.tsx
  src/components/BoothDetail/OuterScrollView/OuterScrollView.tsx
  src/components/BoothDetail/OuterScrollView/index.tsx
  src/components/BoothDetail/PhotoConditionOrganism/PhotoConditionOrganism.tsx
  src/components/BoothDetail/PhotoConditionOrganism/index.tsx
  src/components/BoothDetail/ReviewOrganism/ReviewOrganism.styles.tsx
  src/components/BoothDetail/ReviewOrganism/ReviewOrganism.tsx
  src/components/BoothDetail/StarScoreOrganism/StarScoreOrganism.styles.tsx
  src/components/BoothDetail/StarScoreOrganism/StarScoreOrganism.tsx
  src/components/BoothDetail/StarScoreOrganism/index.tsx
  src/components/utils/KeywordBox/KeywordBox.styles.tsx
  src/components/utils/KeywordBox/KeywordBox.tsx
  src/components/utils/Pressables/PressableIcons.tsx
  src/components/utils/ReviewSummary/ReviewSummary.styles.tsx
  src/components/utils/ReviewSummary/ReviewSummary.tsx
  src/icons/LikeIcon.tsx
  src/icons/NavigationIcon.tsx
  src/icons/PinIcon.tsx
  src/icons/StarIcon20.tsx
  src/querys/useGetInfiniteReviews.ts
  src/querys/useGetPhotoBooth.ts
  src/querys/useGetPostsByTag.ts
  src/querys/useGetReviewImages.ts
  src/screens/BoothScreen/BoothDetailScreen.styles.tsx
  src/screens/BoothScreen/BoothDetailScreen.tsx
  src/styles/Theme.ts
  src/types/index.d.ts
Labels: feature ✨, BoothDetail 📖

#166 [#154] 포스트 작성 api 연동 (POST /post)
  src/apis/getUser.ts
  src/apis/mutatePost.ts
  src/components/Chip/FilterChip.styles.tsx
  src/components/Chip/FilterChip.tsx
  src/components/PostWrite/AddPhotoOrganism/AddPhotoOrganism.styles.tsx
  src/components/PostWrite/AddPhotoOrganism/AddPhotoOrganism.tsx
  src/components/PostWrite/DirectTagSummaryOrganism/DirectTagSummaryOrganism.tsx
  src/components/utils/TabBar/PostWriteTabBar.tsx
  src/querys/useMutatePost.ts
  src/redux/actions/PostWriteAction.ts
  src/redux/reducers/postWriteReducer.ts
  src/types/index.d.ts
  src/types/post.d.ts
  src/types/tag.d.ts
Labels: feature ✨

#171 [#168] 부스 페이지 전체 수정
  src/apis/getPhotoBoothLocation.ts
  src/assets/images/focusedMarker.png
  src/assets/images/marker.png
  src/assets/images/markers/Common.png
  src/assets/images/markers/Harufilm.png
  src/assets/images/markers/Insang.png
  src/assets/images/markers/Photogray.png
  src/assets/images/markers/Photoism.png
  src/assets/images/markers/Selfix.png
  src/components/Booth/BoothSummaryView/BoothSummaryView.styles.tsx
  src/components/Booth/BoothSummaryView/BoothSummaryView.tsx
  src/components/Booth/MapBottomSheetOrganism/MapBottomSheetOrganism.styles.tsx
  src/components/Booth/MapBottomSheetOrganism/MapBottomSheetOrganism.tsx
  src/components/Booth/MapFilterOrganism/MapFilterOrganism.tsx
  src/components/Booth/MapLocationSearchList/MapLocationSearchList.tsx
  src/components/Booth/MapNaverMapOrganism/MapNaverMapOrganism.tsx
  src/components/Booth/MapSearchBar/MapSearchBar.tsx
  src/components/Booth/NaverMap/NaverMap.tsx
  src/components/BoothDetail/HeaderOrganism/HeaderOrganism.tsx
  src/components/BoothDetail/KeywordTagSection/KeywordTagSection.tsx
  src/components/utils/DismissDropDownView/DismissDropDownView.tsx
  src/components/utils/DismissDropDownView/index.tsx
  src/icons/ColorStarIcon14.tsx
  src/querys/useGetPhotoBoothLocation.ts
  src/redux/actions/MapAction.ts
  src/redux/reducers/mapReducer.ts
  src/redux/types/MapActionType.ts
  src/screens/BoothScreen/BoothDetailScreen.tsx
  src/screens/BoothScreen/BoothScreen.header.tsx
  src/screens/BoothScreen/index.tsx
  src/utils/getIconMarker.ts
  src/utils/getMarkerColor.ts
Labels: feature ✨

#169 [#167] 포스트 리스트 API 연동
  src/apis/getPostsByTag.ts
  src/components/PostListDetail/CardListOrganism/CardListOrganism.styles.tsx
  src/components/PostListDetail/CardListOrganism/CardListOrganism.tsx
  src/components/PostListDetail/CardListOrganism/SortingListHeader.tsx
  src/components/PostListDetail/FilterSheetFooter/FilterSheetFooter.tsx
  src/components/Recommend/FeedCard/RecommendFeedCard.tsx
  src/components/Recommend/PreviewSixCard/RecommendPreviewFourCard.tsx
  src/constants/filters.ts
  src/querys/useGetInfinitePosts.ts
  src/redux/actions/PostAction.ts
  src/redux/reducers/postReducer.ts
  src/redux/types/PostActionType.ts
Labels: feature ✨

#174 [#173] 네비게이션 커스텀 탭바 디자인 수정
  AppInner.tsx
  src/components/utils/TabBar/TabBar.styles.tsx
  src/components/utils/TabBar/TabBar.tsx
  src/icons/FocusedNavigation/FocusedBoothIcon.tsx
  src/icons/FocusedNavigation/FocusedRecommendNavIcon.tsx
  src/icons/FocusedNavigation/FocusedRecordIcon.tsx
  src/icons/FocusedNavigation/FocusedStorageIcon.tsx
  src/icons/Navigation/BoothNavIcon.tsx
  src/icons/Navigation/RecommendNavIcon.tsx
  src/icons/Navigation/RecordNavIcon.tsx
  src/icons/Navigation/StorageNavIcon.tsx
Labels: feature ✨

#179 [#177] 찜 화면 수정 및 컴포넌트 구현
  src/apis/getPhotoBooth.ts
  src/apis/mutatePhotoBoothLike.ts
  src/components/BoothDetail/DescriptionOrganism/DescriptionOrganism.tsx
  src/components/Storage/BoothOrganism/BoothOrganism.styles.tsx
  src/components/Storage/BoothOrganism/BoothOrganism.tsx
  src/components/Storage/BoothOrganism/index.tsx
  src/components/Storage/PhotoOrganism/PhotoOrganism.tsx
  src/components/Storage/StorageBoothCard/StorageBoothCard.styles.tsx
  src/components/Storage/StorageBoothCard/StorageBoothCard.tsx
  src/components/Storage/StorageBoothCard/index.tsx
  src/components/Storage/SwipeOrganism/SwipeOrganism.tsx
  src/components/utils/Button/OnlyLikeButton/LikeButton.styles.tsx
  src/components/utils/Button/OnlyLikeButton/LikeButton.tsx
  src/components/utils/Button/OnlyLikeButton/index.tsx
  src/icons/BorderLikeHeartIcon.tsx
  src/querys/useMutatePhotoBoothLike.ts
  src/screens/RecommendScreen/index.tsx
  src/types/index.d.ts
Labels: feature ✨

#178 [#176] 포스트 상세 스크린 구현
  src/apis/getPost.ts
  src/apis/getPosts.ts
  src/components/DiffUserPost/PostListOrganism/PostListOrganism.styles.tsx
  src/components/DiffUserPost/PostListOrganism/PostListOrganism.tsx
  src/components/DiffUserPost/PostListOrganism/index.tsx
  src/components/PostListDetail/CardListOrganism/CardListOrganism.tsx
  src/components/Recommend/FeedCard/RecommendFeedCard.tsx
  src/components/Recommend/PoseOrganism/PoseOrganism.tsx
  src/components/RecommendDetail/ContentsOrganism/ContentsOrganism.styles.tsx
  src/components/RecommendDetail/ContentsOrganism/ContentsOrganism.tsx
  src/components/RecommendDetail/DiffOrganism/DiffOrganism.styles.tsx
  src/components/RecommendDetail/DiffOrganism/DiffOrganism.tsx
  src/components/RecommendDetail/MainFrame/RecommendDetailMainFrame.tsx
  src/components/utils/Button/LikeButton/SimpleLikeButton.tsx
  src/components/utils/TabBar/PostWriteTabBar.tsx
  src/components/utils/UserReviewView/UserReviewView.styles.tsx
  src/components/utils/UserReviewView/UserReviewView.tsx
  src/icons/LikeIcon.tsx
  src/querys/useGetPost.ts
  src/querys/useGetPosts.ts
  src/querys/useGetPostsByUserId.ts
  src/screens/RecommendScreen/DiffUserPostScreen.tsx
  src/screens/RecommendScreen/RecommendDetailScreen.header.tsx
  src/screens/RecommendScreen/RecommendDetailScreen.tsx
  src/screens/RecommendScreen/index.tsx
  src/utils/toDateFormat.ts
Labels: feature ✨

#180 [#175] Filter Sheet 변경된 디자인 반영 및 최적화
  src/components/PostListDetail/CardListOrganism/CardListOrganism.tsx
  src/components/PostListDetail/FilterPages/BrandFilter/BrandFilter.tsx
  src/components/PostListDetail/FilterPages/FrameFilter/FrameFilter.tsx
  src/components/PostListDetail/FilterPages/HeadcountFilter/HeadcountFilter.tsx
  src/components/PostListDetail/FilterPages/PoseFilter/PoseFilter.tsx
  src/components/PostListDetail/FilterSheetBackdrop/FilterSheetBackdrop.tsx
  src/components/PostListDetail/FilterSheetFooter/FilterSheetFooter.tsx
  src/components/Recommend/FeedCard/RecommendFeedCard.tsx
  src/components/utils/TabBar/TabBar.tsx
  src/querys/useGetInfinitePosts.ts
  src/querys/useGetTagForm.ts
  src/screens/RecommendScreen/PostListDetailScreen.header.tsx
Labels: enhancement

#190 [#189] 회원가입 및 닉네임 변경 로직 수정
  src/apis/getUserNameValid.ts
  src/apis/login.ts
  src/components/Recommend/AddPostButton/AddPostButton.styles.tsx
  src/components/Record/AddPostButton/AddPostButton.styles.tsx
  src/components/Record/EditNickNameHeader/EditNickNameHeader.tsx
  src/components/Record/EditNickNameOrganism/EditNickNameOrganism.tsx
  src/components/Record/NickNameView/NickNameView.styles.tsx
  src/components/Record/NickNameView/NickNameView.tsx
  src/components/Setting/SettingOrganism/SettingOrganism.tsx
  src/icons/EclipseStarIcon.tsx
  src/icons/PlusIcon32.tsx
  src/querys/useDeleteUser.ts
  src/screens/RecommendScreen/index.tsx
Labels: feature ✨

#183 [#182] Recommend Screen 중복 헤더 삭제 및 interceptor 실행 순서 보장
  AppInner.tsx
  src/components/PostListDetail/FilterSheetBackdrop/FilterSheetBackdrop.tsx
  src/components/PostListDetail/FilterSheetOrganism/FilterSheetOrganism.tsx
  src/components/Recommend/FeedCard/RecommendFeedCard.tsx
  src/components/utils/Interceptor/index.tsx
  src/querys/useGetPosts.ts
  src/redux/actions/UserAction.ts
  src/redux/reducers/userReducer.ts
  src/redux/types/UserActionType.ts
  src/screens/RecommendScreen/PostListDetailScreen.header.tsx
  src/screens/RecommendScreen/PostListDetailScreen.tsx
  src/screens/RecommendScreen/index.tsx
Labels: feature ✨

#187 [#186] "이 매장에서 찍은 사진" 스크린 구현
  src/apis/getReviewImages.ts
  src/apis/mutatePostLike.ts
  src/components/BoothDetail/BoothImageList/BoothImageList.styles.tsx
  src/components/BoothDetail/BoothImageList/BoothImageList.tsx
  src/components/BoothDetail/BoothImageList/index.tsx
  src/components/BoothDetail/BoothImageOrganism/BoothImageOrganism.tsx
  src/components/BoothDetail/BoothImageOrganism/index.tsx
  src/components/BoothDetail/GridPhotoOrganism/GridPhotoOrganism.styles.tsx
  src/components/BoothDetail/GridPhotoOrganism/GridPhotoOrganism.tsx
  src/components/BoothDetail/OuterScrollView/OuterScrollView.tsx
  src/components/BoothDetail/ReviewOrganism/ReviewOrganism.tsx
  src/components/PostListDetail/CardListOrganism/CardListOrganism.styles.tsx
  src/components/ReviewImageDetail/ReviewListOrganism/ReviewListOrganism.styles.tsx
  src/components/ReviewImageDetail/ReviewListOrganism/ReviewListOrganism.tsx
  src/components/ReviewImageDetail/ReviewListOrganism/index.tsx
  src/components/Storage/PhotoOrganism/PhotoOrganism.tsx
  src/components/utils/Button/ScrollUpButton/ScrollUpButton.styles.tsx
  src/components/utils/Button/ScrollUpButton/ScrollUpButton.tsx
  src/components/utils/Button/ScrollUpButton/index.tsx
  src/components/utils/Pressables/PressableIcons.tsx
  src/icons/CloseIcon.tsx
  src/icons/LeftArrowIcon.tsx
  src/icons/RightArrowIcon.tsx
  src/icons/UpArrowIcon.tsx
  src/querys/useGetInfiniteReviews.ts
  src/querys/useGetPhotoBooth.ts
  src/querys/useGetPost.ts
  src/querys/useGetReviewImages.ts
  src/screens/BoothScreen/BoothDetailScreen.tsx
  src/screens/BoothScreen/BoothImageScreen.tsx
  src/screens/BoothScreen/ReviewDetailScreen.tsx
  src/screens/BoothScreen/ReviewImageDetailScreen.styles.tsx
  src/screens/BoothScreen/ReviewImageDetailScreen.tsx
  src/screens/BoothScreen/index.tsx
Labels: feature ✨

#193 [#192] ActivityIndicator 적용
  src/components/DefaultScrollView/DefaultScrollView.styles.tsx
  src/components/PostListDetail/CardListOrganism/CardListOrganism.styles.tsx
  src/components/PostListDetail/CardListOrganism/CardListOrganism.tsx
  src/components/Recommend/FrameOrganism/FrameOrganism.tsx
  src/components/Recommend/PoseOrganism/PoseOrganism.styles.tsx
  src/components/Recommend/PoseOrganism/PoseOrganism.tsx
  src/components/Recommend/PreviewSixCard/RecommendPreviewFourCard.tsx
  src/components/Record/RecordOrganism/RecordOrganism.styles.tsx
  src/components/Record/RecordOrganism/RecordOrganism.tsx
  src/components/Storage/BoothOrganism/BoothOrganism.tsx
  src/components/Storage/PhotoOrganism/PhotoOrganism.styles.tsx
  src/components/Storage/PhotoOrganism/PhotoOrganism.tsx
  src/components/Storage/SwipeOrganism/SwipeOrganism.tsx
  src/querys/useGetInfinitePosts.ts
Labels: feature ✨

#188 [#181] 부스 지도 바텀 탭 아이콘 수정
  src/assets/images/markers/Common.png
  src/assets/images/markers/Cube_Haru-Film.png
  src/assets/images/markers/Cube_Insalnecut.png
  src/assets/images/markers/Cube_None.png
  src/assets/images/markers/Cube_Photogray.png
  src/assets/images/markers/Cube_Photoism.png
  src/assets/images/markers/Cube_Selfix.png
  src/assets/images/markers/Harufilm.png
  src/assets/images/markers/Insang.png
  src/assets/images/markers/Marker_Haru-Film.png
  src/assets/images/markers/Marker_Insalnecut.png
  src/assets/images/markers/Marker_None.png
  src/assets/images/markers/Marker_Photogray.png
  src/assets/images/markers/Marker_Photoism.png
  src/assets/images/markers/Marker_Selfix.png
  src/assets/images/markers/Photogray.png
  src/assets/images/markers/Photoism.png
  src/assets/images/markers/Selfix.png
  src/components/Booth/BoothSummaryView/BoothSummaryView.styles.tsx
  src/components/Booth/BoothSummaryView/BoothSummaryView.tsx
  src/components/Booth/MapBottomSheetOrganism/MapBottomSheetOrganism.tsx
  src/components/Booth/MapNaverMapOrganism/MapNaverMapOrganism.styles.tsx
  src/components/Booth/MapNaverMapOrganism/MapNaverMapOrganism.tsx
  src/components/Booth/NaverMap/NaverMap.tsx
  src/querys/useGetPhotoBoothLocation.ts
  src/utils/getIconCube.ts
  src/utils/getIconMarker.ts
Labels: feature ✨

#200 [#181] 부스 리뷰 작성 api 연동
  src/apis/getReviewTag.ts
  src/apis/mutateReview.ts
  src/components/BoothReview/ReviewCompleteOrganism/ReviewCompleteOrganism.tsx
  src/components/BoothReview/ReviewImageOrganism/ReviewImageOrganism.tsx
  src/components/BoothReview/ReviewRatingOrganism/ReviewRatingOrganism.tsx
  src/components/BoothReview/ReviewResultOrganism/ReviewResultOrganism.styles.tsx
  src/components/BoothReview/ReviewResultOrganism/ReviewResultOrganism.tsx
  src/components/BoothReview/ReviewSelectPressable/ReviewSelectPressable.styles.tsx
  src/components/BoothReview/ReviewSelectPressable/ReviewSelectPressable.tsx
  src/components/BoothReview/ReviewTagOrganism/ReviewTagOrganism.styles.tsx
  src/components/BoothReview/ReviewTagOrganism/ReviewTagOrganism.tsx
  src/components/SearchTagInput/TagInput/TagInput.tsx
  src/components/utils/ActivityIndicator/ActivityIndicator.styles.tsx
  src/components/utils/ActivityIndicator/ActivityIndicator.tsx
  src/components/utils/ActivityIndicator/index.tsx
  src/querys/useGetReviewTag.ts
  src/querys/useMutateReview.ts
  src/redux/actions/ReviewAction.ts
  src/redux/reducers/reviewReducer.ts
  src/screens/BoothScreen/BoothDetailScreen.tsx
  src/screens/BoothScreen/PostReviewScreen/BoothTagInputScreen.tsx
  src/screens/BoothScreen/PostReviewScreen/index.tsx
  src/types/post.d.ts
Labels: feature ✨

#202 [#201] 추천 페이지 일러스트 추가
  src/assets/images/RecommendScreen/Banner_Home_01.png
  src/assets/images/RecommendScreen/Banner_Home_02.png
  src/assets/images/RecommendScreen/Icon_Home_Hot.png
  src/assets/images/RecommendScreen/Icon_Home_Tag.png
  src/assets/images/RecommendScreen/Icon_Home__Character.png
  src/assets/images/RecommendScreen/Wordmark.png
  src/assets/images/reviewBanner.png
  src/components/Recommend/FrameOrganism/FrameOrganism.styles.tsx
  src/components/Recommend/FrameOrganism/FrameOrganism.tsx
  src/components/Recommend/PoseOrganism/PoseOrganism.styles.tsx
  src/components/Recommend/PoseOrganism/PoseOrganism.tsx
  src/components/Recommend/RecommendCommonBanner/RecommendCommonBanner.styles.tsx
  src/components/Recommend/RecommendCommonBanner/RecommendCommonBanner.tsx
  src/components/Recommend/RecommendHeader/RecommendHeader.styles.tsx
  src/components/Recommend/RecommendHeader/RecommendHeader.tsx
  src/components/Recommend/RecommendKeywordQuest/RecommendKeywordQuest.styles.tsx
  src/components/Recommend/RecommendKeywordQuest/RecommendKeywordQuest.tsx
  src/components/Recommend/ReviewBoothPressableBanner/ReviewBoothPressableBanner.tsx
Labels: feature ✨

#204 [#203] 부스 지도 페이지 일러스트 추가
  src/assets/images/Booth/Except_Image.png
  src/assets/images/Booth/brandDropdown.png
  src/components/Booth/BoothSummaryView/BoothSummaryView.styles.tsx
  src/components/Booth/BoothSummaryView/BoothSummaryView.tsx
  src/components/Booth/MapBottomSheetOrganism/MapBottomSheetOrganism.tsx
  src/components/Booth/MapFilterOrganism/MapFilterOrganism.styles.tsx
  src/components/Chip/MapFilterBrandChip.styles..tsx
  src/components/Chip/MapFilterBrandChip.tsx
  src/types/index.d.ts
Labels: feature ✨

#185 [#184] 포스트 수정 기능 구현
  src/apis/deletePost.ts
  src/apis/patchPost.ts
  src/components/PostWrite/AddPhotoOrganism/AddPhotoOrganism.tsx
  src/components/PostWrite/DirectTagSummaryOrganism/DirectTagSummaryOrganism.tsx
  src/components/PostWrite/ExitCenterOrganism/ExitCenterOrganism.tsx
  src/components/PostWrite/ExitNavigationOrganism/ExitNavigationOrganism.tsx
  src/components/PostWrite/InputCustomTagOrganism/InputCustomTagOrganism.tsx
  src/components/PostWrite/SelectTagSummaryOrganism/SelectTagSummaryOrganism.tsx
  src/components/Recommend/FrameOrganism/FrameOrganism.styles.tsx
  src/components/Recommend/FrameOrganism/FrameOrganism.tsx
  src/components/Recommend/PoseOrganism/PoseOrganism.styles.tsx
  src/components/Recommend/PoseOrganism/PoseOrganism.tsx
  src/components/Recommend/PreviewSixCard/RecommendPreviewFourCard.styles.tsx
  src/components/Recommend/PreviewSixCard/RecommendPreviewFourCard.tsx
  src/components/RecommendDetail/DiffOrganism/DiffOrganism.tsx
  src/components/utils/DropdownMenu/DropdownMenu.tsx
  src/components/utils/Header/LeftBackHeader.styles.tsx
  src/components/utils/Header/LeftBackHeader.tsx
  src/components/utils/ReviewSummary/ReviewSummary.styles.tsx
  src/components/utils/ReviewSummary/ReviewSummary.tsx
  src/components/utils/TabBar/PostWriteTabBar.tsx
  src/icons/MeetBallIcon.tsx
  src/querys/useDeletePost.ts
  src/querys/useModifyPost.ts
  src/redux/actions/PostWriteAction.ts
  src/redux/reducers/postWriteReducer.ts
  src/redux/types/PostWriteActionType.ts
  src/screens/RecommendScreen/PostWriteScreen/SummaryScreen.tsx
  src/screens/RecommendScreen/PostWriteScreen/index.tsx
  src/screens/RecommendScreen/RecommendDetailScreen.header.tsx
  src/screens/RecommendScreen/RecommendDetailScreen.tsx
  src/screens/RecommendScreen/index.tsx
  src/types/index.d.ts
  src/types/post.d.ts
Labels: feature ✨

#199 [#198] 각종 일러스트 추가 및 토스트 컴포넌트 구현
  src/assets/images/boothDetailBanner/empty_booth_image.png
  src/assets/images/boothDetailBanner/stars_0.png
  src/assets/images/boothDetailBanner/stars_1.png
  src/assets/images/boothDetailBanner/stars_2.png
  src/assets/images/boothDetailBanner/stars_3.png
  src/assets/images/boothDetailBanner/stars_4.png
  src/assets/images/boothDetailBanner/stars_5.png
  src/assets/images/logo/word_logo.png
  src/components/BoothDetail/ImageSliderOrganism/ImageSliderOrganism.tsx
  src/components/BoothDetail/StarScoreOrganism/StarScoreOrganism.styles.tsx
  src/components/BoothDetail/StarScoreOrganism/StarScoreOrganism.tsx
  src/components/Chip/FilterChip.styles.tsx
  src/components/Chip/FilterChip.tsx
  src/components/Login/LoginHeader/LoginHeader.tsx
  src/components/Login/LoginOrganism/LoginOrganism.styles.tsx
  src/components/Login/LoginOrganism/LoginOrganism.tsx
  src/components/PostListDetail/FilterPages/BrandFilter/BrandFilter.styles.tsx
  src/components/PostListDetail/FilterPages/HeadcountFilter/HeadcountFilter.tsx
  src/components/PostListDetail/FilterPages/NestedFilterOrganism/NestedFilterOrganism.styles.tsx
  src/components/PostListDetail/FilterSheetNavigator/FilterSheetNavigator.styles.tsx
  src/components/PostWrite/DirectTagSummaryOrganism/DirectTagSummaryOrganism.tsx
  src/components/PostWrite/SelectTagSummaryOrganism/SelectTagSummaryOrganism.tsx
  src/components/Recommend/AddPostButton/AddPostButton.styles.tsx
  src/components/utils/Toast/Toast.styles.tsx
  src/components/utils/Toast/Toast.tsx
  src/components/utils/Toast/index.tsx
  src/icons/CloseIcon.tsx
  src/icons/LikeHeartIcon.tsx
  src/icons/StarIcon20.tsx
  src/utils/getBoothBanner.ts
Labels: feature ✨

#206 [#205] 일러스트 추가
  src/assets/images/end/end_post.png
  src/assets/images/end/end_review.png
  src/assets/images/login/before_login_record.png
  src/assets/images/login/before_login_storage.png
  src/components/BoothReview/ReviewCompleteOrganism/ReviewCompleteOrganism.styles.tsx
  src/components/BoothReview/ReviewCompleteOrganism/ReviewCompleteOrganism.tsx
  src/components/PostWrite/ExitCenterOrganism/ExitCenterOrganism.styles.tsx
  src/components/PostWrite/ExitCenterOrganism/ExitCenterOrganism.tsx
  src/components/Record/RecordOrganism/RecordOrganism.tsx
  src/components/Storage/SwipeOrganism/SwipeOrganism.tsx
  src/components/utils/NotLoginContainer/NotLoginContainer.styles.tsx
  src/components/utils/NotLoginContainer/NotLoginContainer.tsx
Labels: feature ✨

#197 [#196] 안드로이드 App Icon 적용
  android/app/src/main/res/drawable/ic_launcher_background.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: feature ✨

#195 [#194] 스플래시 스크린 적용
  AppInner.tsx
  android/app/build.gradle
  android/app/src/main/java/com/hot6/MainActivity.java
  android/app/src/main/java/com/hot6/MainApplication.java
  android/app/src/main/res/drawable-hdpi/launch_left.png
  android/app/src/main/res/drawable-hdpi/launch_right.png
  android/app/src/main/res/drawable-hdpi/launch_screen.png
  android/app/src/main/res/drawable-mdpi/launch_left.png
  android/app/src/main/res/drawable-mdpi/launch_right.png
  android/app/src/main/res/drawable-mdpi/launch_screen.png
  android/app/src/main/res/drawable-xhdpi/launch_left.png
  android/app/src/main/res/drawable-xhdpi/launch_right.png
  android/app/src/main/res/drawable-xhdpi/launch_screen.png
  android/app/src/main/res/drawable-xxhdpi/launch_left.png
  android/app/src/main/res/drawable-xxhdpi/launch_right.png
  android/app/src/main/res/drawable-xxhdpi/launch_screen.png
  android/app/src/main/res/drawable-xxxhdpi/launch_left.png
  android/app/src/main/res/drawable-xxxhdpi/launch_right.png
  android/app/src/main/res/drawable-xxxhdpi/launch_screen.png
  android/app/src/main/res/drawable/launch_left.png
  android/app/src/main/res/drawable/launch_right.png
  android/app/src/main/res/drawable/launch_screen.png
  android/app/src/main/res/layout/launch_screen.xml
  android/settings.gradle
  ios/Podfile.lock
  ios/hot6.xcodeproj/project.pbxproj
  ios/hot6/AppDelegate.mm
  ios/hot6/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/hot6/Images.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/hot6/Images.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/hot6/Images.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/hot6/Images.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/hot6/Images.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ios/hot6/Images.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/hot6/Images.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ios/hot6/Images.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ios/hot6/Images.xcassets/AppIcon.appiconset/iTunesArtwork@2x.png
  ios/hot6/Images.xcassets/Contents.json
  ios/hot6/Images.xcassets/SplashIcon.imageset/Contents.json
  ios/hot6/Images.xcassets/SplashIcon.imageset/_스플래시_로고-1.png
  ios/hot6/Images.xcassets/SplashIcon.imageset/_스플래시_로고-2.png
  ios/hot6/Images.xcassets/SplashIcon.imageset/_스플래시_로고.png
  ios/hot6/Images.xcassets/SplashLeft.imageset/Contents.json
  ios/hot6/Images.xcassets/SplashLeft.imageset/_스플래시_왼쪽상단-1.png
  ios/hot6/Images.xcassets/SplashLeft.imageset/_스플래시_왼쪽상단-2.png
  ios/hot6/Images.xcassets/SplashLeft.imageset/_스플래시_왼쪽상단.png
  ios/hot6/Images.xcassets/SplashRight.imageset/Contents.json
  ios/hot6/Images.xcassets/SplashRight.imageset/_스플래시_오른쪽 상단-1.png
  ios/hot6/Images.xcassets/SplashRight.imageset/_스플래시_오른쪽 상단-2.png
  ios/hot6/Images.xcassets/SplashRight.imageset/_스플래시_오른쪽 상단.png
  ios/hot6/LaunchScreen.storyboard
  package.json
  src/apis/getUser.ts
  src/components/Login/LoginOrganism/LoginOrganism.tsx
  src/querys/useGetPosts.ts
  yarn.lock
Labels: feature ✨

#217 [#214] 2차 마무리 작업 진행
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  src/components/Recommend/PoseOrganism/PoseOrganism.tsx
  src/components/utils/LineSlideView/LineSlideView.tsx
  src/querys/useGetInfinitePosts.ts
  src/querys/useGetPosts.ts
  src/querys/useGetReviewImages.ts
  src/querys/useMutatePhotoBoothLike.ts
  src/querys/useMutatePostLike.ts
  src/querys/useMutateReviewImageLike.ts
Labels: feature ✨

#211 [#210] update & create 작업이 success 된 이후에 작업이 처리되도록 구현
  src/components/BoothReview/ReviewImageOrganism/ReviewImageOrganism.tsx
  src/components/Chip/TagInputChip.styles.tsx
  src/components/PostWrite/SelectSharedScopeOrganism/SelectSharedScopeOrganism.styles.tsx
  src/components/PostWrite/SelectTagOrganism/SelectTagOrganism.styles.tsx
  src/components/PostWrite/SelectTagOrganism/SelectTagOrganism.tsx
  src/components/PostWrite/SelectTagSection/SelectTagSection.styles.tsx
  src/components/PostWrite/SelectTagSummaryOrganism/SelectTagSummaryOrganism.styles.tsx
  src/components/Recommend/AddPostButton/AddPostButton.styles.tsx
  src/components/Recommend/ReviewBoothPressableBanner/ReviewBoothPressableBanner.styles.tsx
  src/components/Record/NickNameView/NickNameView.styles.tsx
  src/components/Record/RecordHeader/RecordHeader.styles.tsx
  src/components/Record/RecordHeader/RecordHeader.tsx
  src/components/SearchTagInput/TagInput/TagInput.styles.tsx
  src/components/utils/Button/LikeButton/LikeButton.tsx
  src/components/utils/TabBar/PostWriteTabBar.tsx
  src/components/utils/TabBar/TabBar.tsx
  src/icons/WarningIcon.tsx
  src/screens/RecommendScreen/PostWriteScreen/AddPhotoScreen.tsx
  src/styles/Theme.ts
Labels: feature ✨

#212 [#208] 접근권한 스크린 구현
  App.tsx
  AppInner.tsx
  ios/Podfile.lock
  ios/hot6.xcodeproj/project.pbxproj
  package.json
  src/components/Booth/MapNaverMapOrganism/MapNaverMapOrganism.tsx
  src/components/BoothReview/ReviewCompleteOrganism/ReviewCompleteOrganism.tsx
  src/components/BoothReview/ReviewImageOrganism/ReviewImageOrganism.tsx
  src/components/PermissionOrganism/PermissionOrganism.styles.tsx
  src/components/PermissionOrganism/PermissionOrganism.tsx
  src/components/PermissionOrganism/index.tsx
  src/components/PostWrite/AddPhotoOrganism/AddPhotoOrganism.tsx
  src/hooks/requestLocationPermission.ts
  src/hooks/requestcameraPermission.ts
  src/hooks/useCameraPermission.ts
  src/icons/Permission/CameraIcon.tsx
  src/icons/Permission/FileIcon.tsx
  src/icons/Permission/LocationIcon.tsx
  src/icons/Permission/PhoneIcon.tsx
  src/screens/PermissionScreen/PermissionScreen.tsx
  src/screens/PermissionScreen/index.tsx
  yarn.lock
Labels: feature ✨

#215 [#213] ios 앱 아이콘 및 스플래시 스크린 재 구현
  ios/hot6/Images.xcassets/AppIcon.appiconset/120-1.png
  ios/hot6/Images.xcassets/AppIcon.appiconset/120.png
  ios/hot6/Images.xcassets/AppIcon.appiconset/180.png
  ios/hot6/Images.xcassets/AppIcon.appiconset/40.png
  ios/hot6/Images.xcassets/AppIcon.appiconset/58.png
  ios/hot6/Images.xcassets/AppIcon.appiconset/60.png
  ios/hot6/Images.xcassets/AppIcon.appiconset/80.png
  ios/hot6/Images.xcassets/AppIcon.appiconset/87.png
  ios/hot6/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/hot6/Images.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/hot6/Images.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/hot6/Images.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/hot6/Images.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/hot6/Images.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ios/hot6/Images.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/hot6/Images.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ios/hot6/Images.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ios/hot6/Images.xcassets/AppIcon.appiconset/appstore.png
  ios/hot6/Images.xcassets/AppIcon.appiconset/iTunesArtwork@2x.png
  ios/hot6/Images.xcassets/SplashIcon.imageset/Contents.json
  ios/hot6/Images.xcassets/SplashIcon.imageset/splash_logo-1.png
  ios/hot6/Images.xcassets/SplashIcon.imageset/splash_logo-2.png
  ios/hot6/Images.xcassets/SplashIcon.imageset/splash_logo.png
  ios/hot6/Images.xcassets/SplashLeft.imageset/Contents.json
  ios/hot6/Images.xcassets/SplashLeft.imageset/splash_left-1.png
  ios/hot6/Images.xcassets/SplashLeft.imageset/splash_left-2.png
  ios/hot6/Images.xcassets/SplashLeft.imageset/splash_left.png
  ios/hot6/Images.xcassets/SplashRight.imageset/Contents.json
  ios/hot6/Images.xcassets/SplashRight.imageset/splash_right-1.png
  ios/hot6/Images.xcassets/SplashRight.imageset/splash_right-2.png
  ios/hot6/Images.xcassets/SplashRight.imageset/splash_right.png
Labels: feature ✨

#218 [#216] 2차 작업 디자인 수정 및 각종 오류 수정
  src/apis/getSearchedTag.ts
  src/apis/mutateReviewImageLike.ts
  src/components/Booth/BoothSummaryView/BoothSummaryView.tsx
  src/components/Booth/MapBottomSheetOrganism/MapBottomSheetOrganism.styles.tsx
  src/components/Booth/MapFilterOrganism/MapFilterOrganism.styles.tsx
  src/components/Booth/MapFilterOrganism/MapFilterOrganism.tsx
  src/components/Booth/MapNaverMapOrganism/MapNaverMapOrganism.tsx
  src/components/Booth/MapSearchBar/MapSearchBar.styles.tsx
  src/components/Booth/NaverMap/NaverMap.tsx
  src/components/BoothDetail/BoothImageList/BoothImageList.tsx
  src/components/BoothDetail/DescriptionOrganism/DescriptionOrganism.tsx
  src/components/BoothDetail/OuterScrollView/OuterScrollView.tsx
  src/components/BoothDetail/StarScoreOrganism/StarScoreOrganism.tsx
  src/components/Chip/MapFilterBrandChip.styles..tsx
  src/components/Chip/MapFilterChip.styles.tsx
  src/components/PostWrite/AddPhotoOrganism/AddPhotoOrganism.tsx
  src/components/Recommend/AddPostButton/AddPostButton.tsx
  src/components/Recommend/FrameOrganism/FrameOrganism.tsx
  src/components/Record/AddPostButton/AddPostButton.tsx
  src/components/Record/RecordOrganism/RecordOrganism.styles.tsx
  src/components/Record/RecordOrganism/RecordOrganism.tsx
  src/hooks/useFilteredItem.ts
  src/querys/useGetPhotoBoothLocation.ts
  src/querys/useMutateReviewImageLike.ts
  src/types/index.d.ts
Labels: feature ✨

#220 [#210] 부스 리뷰 수정 기능 구현
  src/apis/deleteReview.ts
  src/apis/patchReview.ts
  src/components/BoothDetail/GridPhotoOrganism/GridPhotoOrganism.tsx
  src/components/BoothDetail/StarScoreOrganism/StarScoreOrganism.tsx
  src/components/BoothReview/ReviewImageOrganism/ReviewImageOrganism.tsx
  src/components/BoothReview/ReviewRatingOrganism/ReviewRatingOrganism.tsx
  src/components/Record/RecordOrganism/RecordOrganism.tsx
  src/components/utils/ReviewSummary/ReviewSummary.tsx
  src/querys/useDeleteReview.ts
  src/querys/usePatchReview.ts
  src/redux/actions/ReviewAction.ts
  src/redux/reducers/reviewReducer.ts
  src/redux/types/ReviewActionType.ts
  src/screens/RecommendScreen/RecommendScreen.tsx
  src/types/index.d.ts
  src/types/post.d.ts
  src/types/review.d.ts
Labels: feature ✨

#221 [#219] 각종 버그 해결
  src/components/Booth/MapNaverMapOrganism/MapNaverMapOrganism.tsx
  src/components/Login/LoginOrganism/LoginOrganism.tsx
  src/components/Record/RecordHeader/RecordHeader.styles.tsx
  src/components/Record/RecordHeader/RecordHeader.tsx
  src/components/Record/RecordOrganism/RecordOrganism.styles.tsx
  src/components/Record/RecordOrganism/RecordOrganism.tsx
  src/components/Setting/SettingOrganism/SettingOrganism.tsx
  src/components/Storage/BoothOrganism/BoothOrganism.styles.tsx
  src/components/Storage/BoothOrganism/BoothOrganism.tsx
  src/components/Storage/PhotoOrganism/PhotoOrganism.styles.tsx
  src/components/Storage/PhotoOrganism/PhotoOrganism.tsx
  src/components/Storage/SwipeOrganism/SwipeOrganism.tsx
  src/components/utils/Interceptor/index.tsx
Labels: bug

#230 [#228] 앱 이름 수정
  android/app/src/main/res/values/strings.xml
  app.json
  ios/hot6/Info.plist
Labels: hotfix 🛠

#231 [#229] UI 및 기능 수정
  src/components/PostListDetail/CardListOrganism/SortingListHeader.tsx
  src/components/PostListDetail/FilterOrganism/FilterOrganism.tsx
  src/components/PostListDetail/FilterSheetBackdrop/FilterSheetBackdrop.tsx
  src/components/Recommend/FrameOrganism/FrameOrganism.tsx
  src/redux/reducers/postReducer.ts
Labels: hotfix 🛠

#239 [#233] 시연 영상 hotfix
  src/apis/mutateReviewImageLike.ts
  src/components/BoothDetail/BoothImageList/BoothImageList.tsx
  src/components/BoothDetail/ImageSliderOrganism/ImageSliderOrganism.tsx
  src/components/BoothDetail/OuterScrollView/OuterScrollView.tsx
  src/components/PostWrite/TextFieldOrganism/TextFieldOrganism.tsx
  src/components/Recommend/RecommendKeywordQuest/RecommendKeywordQuest.styles.tsx
  src/components/Recommend/RecommendKeywordQuest/RecommendKeywordQuest.tsx
  src/components/Storage/SwipeOrganism/SwipeOrganism.tsx
  src/querys/useGetPhotoBooth.ts
  src/querys/useMutateReviewImageLike.ts
  src/screens/BoothScreen/PostReviewScreen/BoothTagInputScreen.tsx
  src/screens/RecommendScreen/PostWriteScreen/SummaryScreen.tsx
Labels: hotfix 🛠

#238 [#232] 코드푸쉬 적용
  .gitignore
  App.tsx
  android/app/build.gradle
  android/app/src/main/java/com/hot6/MainApplication.java
  android/app/src/main/res/values/strings.xml
  android/settings.gradle
  ios/Podfile.lock
  ios/hot6.xcodeproj/project.pbxproj
  ios/hot6/AppDelegate.mm
  ios/hot6/Info.plist
  package.json
  yarn.lock
Labels: feature ✨

#237 [#236] 지도 내 api 호출 되지 않는 버그 수정
  src/components/Booth/MapNaverMapOrganism/MapNaverMapOrganism.tsx
Labels: bug, hotfix 🛠

#235 [#234] 애플 로그인 추가
  ios/Podfile.lock
  ios/hot6.xcodeproj/project.pbxproj
  ios/hot6/hot6.entitlements
  package.json
  src/apis/appleLoginBridge.ts
  src/apis/googleLoginBridge.ts
  src/apis/kakaoLoginBridge.ts
  src/assets/images/appleImage.png
  src/components/Login/LoginOrganism/LoginOrganism.styles.tsx
  src/components/Login/LoginOrganism/LoginOrganism.tsx
  yarn.lock
Labels: feature ✨

#240 [#232] fix git ignore
  .gitignore
Labels: bug

#242 [#241] 세부 버그 hotfix
  AppInner.tsx
  ios/hot6.xcodeproj/project.pbxproj
  src/apis/appleLoginBridge.ts
  src/components/BoothReview/ReviewImageOrganism/ReviewImageOrganism.tsx
  src/components/PostWrite/AddPhotoOrganism/AddPhotoOrganism.tsx
  src/components/SearchTagInput/TagSearchList/TagSearchList.styles.tsx
  src/components/utils/DismissCommonKeyboardView/DismissCommonKeyboardView.tsx
  src/components/utils/DismissCommonKeyboardView/index.tsx
  src/querys/useGetUserList.ts
  src/screens/BoothScreen/PostReviewScreen/BoothTagInputScreen.tsx
  src/screens/RecommendScreen/PostWriteScreen/CustomTagScreen.tsx
  src/screens/RecommendScreen/RecommendDetailScreen.header.tsx
  src/screens/RecommendScreen/RecommendDetailScreen.tsx
  src/screens/RecommendScreen/index.tsx
Labels: bug, hotfix 🛠

#244 [#243] 다른 유저의 사진 보기 이슈 해결
  src/apis/getPosts.ts
  src/components/Recommend/PoseOrganism/PoseOrganism.tsx
  src/querys/useGetInfinitePosts.ts
Labels: hotfix 🛠

#248 [#247] ios testFlight 설정 및 수정(1)
  ios/hot6.xcodeproj/project.pbxproj
  ios/hot6.xcodeproj/xcshareddata/xcschemes/hot6.xcscheme
  ios/hot6/Images.xcassets/SplashIcon.imageset/_스플래시_로고-1.png
  ios/hot6/Images.xcassets/SplashIcon.imageset/_스플래시_로고-2.png
  ios/hot6/Images.xcassets/SplashIcon.imageset/_스플래시_로고.png
  ios/hot6/Images.xcassets/SplashLeft.imageset/_스플래시_왼쪽상단-1.png
  ios/hot6/Images.xcassets/SplashLeft.imageset/_스플래시_왼쪽상단-2.png
  ios/hot6/Images.xcassets/SplashLeft.imageset/_스플래시_왼쪽상단.png
  ios/hot6/Images.xcassets/SplashRight.imageset/_스플래시_오른쪽 상단-1.png
  ios/hot6/Images.xcassets/SplashRight.imageset/_스플래시_오른쪽 상단-2.png
  ios/hot6/Images.xcassets/SplashRight.imageset/_스플래시_오른쪽 상단.png
  src/components/PostWrite/AddPhotoOrganism/AddPhotoOrganism.tsx
Labels: feature ✨
