Repository dnd-side-project/dnd-7th-6-frontend, pull requests merged in 2022-09, with the labels that each got.

#255 [#251] 브랜드 필터 로직 수정
  AppInner.tsx
  ios/hot6.xcodeproj/project.pbxproj
  ios/hot6.xcodeproj/xcshareddata/xcschemes/hot6.xcscheme
  ios/hot6.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  src/querys/useGetInfinitePosts.ts
  src/querys/useGetUserLike.ts
  src/redux/reducers/mapReducer.ts
Labels: hotfix 🛠

#257 [#252] 포스트 상세 좋아요 수정
  src/components/utils/UserReviewView/UserReviewView.tsx
Labels: hotfix 🛠

#258 [#245] 안드로이드 다크모드 비활성화 및 토큰 로직 수정
  AppInner.tsx
  android/app/src/main/res/values/styles.xml
  src/components/Login/LoginOrganism/LoginOrganism.tsx
  src/components/Record/EditNickNameHeader/EditNickNameHeader.tsx
  src/components/Setting/SettingOrganism/SettingOrganism.tsx
  src/components/utils/Interceptor/index.tsx
  src/hooks/useLogout.ts
Labels: hotfix 🛠

#256 [#254] 글 작성 시 1초 뒤에 버튼의 disabled가 풀려 글 작성 요청을 여러 번 보내는 문제 해결
  src/components/BoothReview/ReviewImageOrganism/ReviewImageOrganism.tsx
  src/components/utils/TabBar/PostWriteTabBar.tsx
Labels: hotfix 🛠

#264 [#260] 추천 스크린 접속 시 좋아요 표시 문제 해결
  src/components/Recommend/PoseOrganism/PoseOrganism.tsx
Labels: hotfix 🛠

#271 [#250] 지도 페이지 brand filter 버그 수정 및 bottom sheet 로직 변경
  src/components/Booth/MapBottomSheetOrganism/MapBottomSheetOrganism.tsx
  src/redux/reducers/mapReducer.ts
Labels: bug

#268 [#267] 당겨서 새로고침 ui 구현
  .gitattributes
  .gitignore
  ios/hot6.xcodeproj/project.pbxproj
  ios/hot6/AppDelegate.mm
  src/components/DefaultScrollView/DefaultScrollView.tsx
  src/components/Recommend/RecommendOrganism/RecommendOrganism.tsx
  src/components/Recommend/RecommendOrganism/index.tsx
  src/screens/RecommendScreen/RecommendScreen.tsx
Labels: feature ✨

#272 [#269] 로그인 & 로그아웃 시 추천 스크린 Post 좋아요 업데이트 안되는 문제 해결
  App.tsx
  AppInner.tsx
  src/components/Recommend/FrameOrganism/FrameOrganism.tsx
  src/components/Recommend/PoseOrganism/PoseOrganism.tsx
  src/components/UserProvider/UserProvider.tsx
  src/components/UserProvider/index.ts
  src/components/utils/Interceptor/index.tsx
  src/hooks/useLogout.ts
  src/redux/actions/UserAction.ts
  src/redux/reducers/userReducer.ts
  src/redux/types/UserActionType.ts
Labels: bug, hotfix 🛠

#273 TestFlight v4 디벨롭 브랜치 to main
  .gitattributes
  .gitignore
  ios/hot6.xcodeproj/project.pbxproj
  ios/hot6/AppDelegate.mm
  src/components/Booth/MapBottomSheetOrganism/MapBottomSheetOrganism.tsx
  src/components/DefaultScrollView/DefaultScrollView.tsx
  src/components/Recommend/RecommendOrganism/RecommendOrganism.tsx
  src/components/Recommend/RecommendOrganism/index.tsx
  src/redux/reducers/mapReducer.ts
  src/screens/RecommendScreen/RecommendScreen.tsx
Labels: config 🛠

#275 [#274] App initial 시 좋아요 안뜨는 문제 해결
  src/apis/getPostsByTag.ts
  src/components/Recommend/FrameOrganism/FrameOrganism.tsx
  src/components/Recommend/PoseOrganism/PoseOrganism.tsx
  src/querys/useGetInfinitePosts.ts
Labels: hotfix 🛠

#276 [#274] fix like in Post Recommend Screen (2)
  src/components/Recommend/FrameOrganism/FrameOrganism.tsx
  src/components/Recommend/PoseOrganism/PoseOrganism.tsx
Labels: hotfix 🛠

#277 [#263] Android build config & PostWrite 뒤로가기 문제 해결
  android/app/build.gradle
  android/gradle.properties
  src/components/utils/TabBar/PostWriteTabBar.tsx
  src/screens/RecommendScreen/PostWriteScreen/AddPhotoScreen.tsx
Labels: hotfix 🛠

#283 [#282] ios 뒤로가기 핸들러로 action 함수가 작동하지 않는 문제 해결
  src/components/PostListDetail/FilterSheetBackdrop/FilterSheetBackdrop.tsx
Labels: bug

#281 [#280] provider refresh token 문제 생겼을 경우 & 로그아웃 및 로그인시 좋아요 refetch 안되는 문제 수정
  src/components/Recommend/FrameOrganism/FrameOrganism.tsx
  src/components/Recommend/PoseOrganism/PoseOrganism.tsx
  src/hooks/useLogout.ts
Labels: bug

#285 [#284] navigation beforeRemove 이벤트 함수 적용 안되는 문제 해결
  src/components/PostListDetail/FilterSheetBackdrop/FilterSheetBackdrop.tsx
Labels: bug
