Repository dnd-side-project/dnd-7th-6-frontend, pull requests merged in 2022-07, with the labels that each got.

#3 chore: ios 초기 세팅
  ios/File.swift
  ios/Podfile.lock
  ios/hot6-Bridging-Header.h
  ios/hot6.xcodeproj/project.pbxproj
  ios/hot6.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/hot6/Info.plist
  package-lock.json
Labels: setting

#4 Feat#1
  .gitmessage.txt
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/hot6/MainActivity.java
  android/build.gradle
  android/gradlew
  package.json
  yarn.lock
Labels: setting

#6 🏗️ build(tsconfig): fix error of absolute path in tsconfig
  babel.config.js
  package.json
  tsconfig.json
  yarn.lock
Labels: bug

#8 🧹 chore(package.json): add react-query & axios
  package.json
  yarn.lock
Labels: wontfix

#10 🐛 fix(eslintrc): modify eslint for no-unresolved error
  .eslintrc.js
Labels: bug

#25 [#13] PressableIcon 컴포넌트 구현
  package.json
  src/components/PressableIcon/PressableIcon.styles.tsx
  src/components/PressableIcon/index.tsx
  src/icons/LikeIcon.tsx
  src/icons/UploadIcon.tsx
Labels: feature ✨

#24 [#11] Chip Util 컴포넌트 구현
  src/components/Chip/Chip.styles.tsx
  src/components/Chip/Chip.tsx
  src/components/Chip/index.tsx
Labels: feature ✨

#23 [#19] 바텀바 구조 설계 & 바텀탭과 스택탭 라이브러리 설치
  App.tsx
  package.json
  src/screens/BoothScreen/BoothScreen.tsx
  src/screens/MyScreen/MyScreen.tsx
  src/screens/RecommendScreen/RecommendScreen.tsx
  src/screens/StorageScreen/StorageScreen.tsx
  yarn.lock
Labels: feature ✨

#29 [#17] 추천 상세 페이지 설명 컴포넌트 구현
  src/components/RecommendDetailContentsOrganism/RecommendDetailContentsOrganism.tsx
  src/components/RecommendDetailContentsOrganism/RecommendDetailContentsOrganisms.styles.tsx
  src/components/RecommendDetailContentsOrganism/index.tsx
  src/icons/LikeIcon.tsx
  src/icons/UploadIcon.tsx
Labels: feature ✨

#28 [#16] 추천 페이지 메인 이미지 컴포넌트 구현
  src/components/RecommendDetailMainFrame/RecommendDetailMainFrame.styles.tsx
  src/components/RecommendDetailMainFrame/RecommendDetailMainFrame.tsx
  src/components/RecommendDetailMainFrame/index.tsx
Labels: feature ✨

#30 [#22] 반응형 웹을 위한 response-dimensions 관련 함수 추가
  package.json
  src/utils/ScreenResponse.ts
  yarn.lock
Labels: feature ✨

#32 [#14] SquareCard 컴포넌트 구현
  src/components/SquareCard/SquareCard.styles.tsx
  src/components/SquareCard/index.tsx
Labels: feature ✨

#33 [#12] RecommendFeedCard 컴포넌트 구현
  ios/Podfile.lock
  ios/hot6.xcodeproj/project.pbxproj
  src/components/RecommendDetailContentsOrganism/RecommendDetailContentsOrganism.tsx
  src/components/RecommendDetailContentsOrganism/RecommendDetailContentsOrganisms.styles.tsx
  src/components/RecommendFeedCard/RecommendFeedCard.styles.tsx
  src/components/RecommendFeedCard/RecommendFeedCard.tsx
  src/components/RecommendFeedCard/index.tsx
  src/components/utils/PressableIcon/PressableIcon.styles.tsx
  src/components/utils/PressableIcon/index.tsx
  src/components/utils/Pressables/PressableIcons.tsx
Labels: setting, feature ✨

#34 [#17] 추천 상세 페이지 설명 영역 API 호출 로직 추가
  .gitignore
  App.tsx
  package.json
  src/apis/getPost.ts
  src/components/RecommendDetailContentsOrganism/RecommendDetailContentsOrganism.styles.tsx
  src/components/RecommendDetailContentsOrganism/RecommendDetailContentsOrganism.tsx
  src/querys/useGetPost.ts
  src/types/index.d.ts
  src/utils/toDateFormat.ts
Labels: feature ✨

#37 [#36] SquareCard 컴포넌트 구조 수정 및 FastImage Library 적용
  src/components/SquareCard/SquareCard.styles.tsx
  src/components/SquareCard/SquareCard.tsx
  src/components/SquareCard/index.tsx
Labels: feature ✨

#39 [#38] theme 추가 및 ScreenResponse 이동 (styles)
  App.tsx
  src/components/PressableAddition/PressableAddition.styles.tsx
  src/components/RecommendFeedCard/RecommendFeedCard.styles.tsx
  src/components/SquareCard/SquareCard.styles.tsx
  src/styles/ScreenResponse.ts
  src/styles/Theme.ts
Labels: bug

#41 [#40] RecommendScreen 페이지 분리
  App.tsx
  src/screens/RecommendScreen/RecommendDetailScreen.tsx
  src/screens/RecommendScreen/RecommendScreen.tsx
  src/screens/RecommendScreen/index.tsx
Labels: feature ✨

#42 [#35] Theme 및 ScreenResponse 적용
  src/components/Chip/Chip.styles.tsx
  src/components/Chip/Chip.tsx
  src/components/RecommendDetailContentsOrganism/RecommendDetailContentsOrganism.styles.tsx
  src/components/RecommendDetailMainFrame/RecommendDetailMainFrame.styles.tsx
Labels: feature ✨

#44 [#43] Theme.ts에 Branding 완료된 폰트 추가
  App.tsx
  android/app/src/main/assets/fonts/Pretendard-Black.ttf
  android/app/src/main/assets/fonts/Pretendard-Bold.ttf
  android/app/src/main/assets/fonts/Pretendard-ExtraBold.ttf
  android/app/src/main/assets/fonts/Pretendard-ExtraLight.ttf
  android/app/src/main/assets/fonts/Pretendard-Light.ttf
  android/app/src/main/assets/fonts/Pretendard-Medium.ttf
  android/app/src/main/assets/fonts/Pretendard-Regular.ttf
  android/app/src/main/assets/fonts/Pretendard-SemiBold.ttf
  android/app/src/main/assets/fonts/Pretendard-Thin.ttf
  ios/Fonts/Pretendard-Black.ttf
  ios/Fonts/Pretendard-Bold.ttf
  ios/Fonts/Pretendard-ExtraBold.ttf
  ios/Fonts/Pretendard-ExtraLight.ttf
  ios/Fonts/Pretendard-Light.ttf
  ios/Fonts/Pretendard-Medium.ttf
  ios/Fonts/Pretendard-Regular.ttf
  ios/Fonts/Pretendard-SemiBold.ttf
  ios/Fonts/Pretendard-Thin.ttf
  ios/hot6.xcodeproj/project.pbxproj
  ios/hot6/Info.plist
  src/styles/Theme.ts
Labels: feature ✨

#46 [#45] Text 유틸 컴포넌트 추가
  src/components/utils/Text/BodyText.tsx
  src/components/utils/Text/Headline.tsx
  src/components/utils/Text/SubHeadline.tsx
  src/components/utils/Text/index.ts
Labels: feature ✨

#49 [#15] PressableAdditionStyle mode props 추가
  src/components/PressableAddition/PressableAddition.styles.tsx
  src/components/PressableAddition/PressableAddition.tsx
Labels: feature ✨

#48 [#18] 유저의 다른 포즈 영역 구현
  src/components/RecommendDetailDiffOrganism/RecommendDetailDiffOrganism.styles.tsx
  src/components/RecommendDetailDiffOrganism/RecommendDetailDiffOrganism.tsx
  src/components/RecommendDetailDiffOrganism/index.tsx
  src/components/utils/Pressables/PressableIcons.tsx
  src/icons/RightArrowIcon.tsx
Labels: feature ✨

#47 [#16] API Request 로직 추가 (RecommendDetailMainFrame)
  src/components/RecommendDetailMainFrame/RecommendDetailMainFrame.styles.tsx
  src/components/RecommendDetailMainFrame/RecommendDetailMainFrame.tsx
Labels: feature ✨

#50 [#20] 4장 미리보기 FeedCard 컴포넌트 추가 & 반응형 디자인 수정
  src/components/RecommendFeedCard/RecommendFeedCard.styles.tsx
  src/components/RecommendPreviewFourCard/RecommendPreviewFourCard.styles.tsx
  src/components/RecommendPreviewFourCard/RecommendPreviewFourCard.tsx
  src/components/RecommendPreviewFourCard/index.tsx
Labels: feature ✨

#52 [#51] 폰트 수정 & 폰트 관련 컴포넌트 수정
  src/components/utils/Text/BodyText.tsx
  src/components/utils/Text/index.ts
  src/styles/Theme.ts
Labels: bug

#53 [#20] 추천 메인 페이지 제작 (미완)
  src/TestData.ts
  src/components/DefaultScrollView/DefaultScrollView.styles.tsx
  src/components/DefaultScrollView/DefaultScrollView.tsx
  src/components/DefaultScrollView/index.tsx
  src/components/FrameRecommendOrganism/FrameRecommendOrganism.styles.tsx
  src/components/FrameRecommendOrganism/FrameRecommendOrganism.tsx
  src/components/FrameRecommendOrganism/index.tsx
  src/components/PoseRecommendOrganism/PoseRecommendOrganism.styles.tsx
  src/components/PoseRecommendOrganism/PoseRecommendOrganism.tsx
  src/components/PoseRecommendOrganism/index.tsx
  src/components/RecommendFeedCard/RecommendFeedCard.styles.tsx
  src/components/RecommendPreviewFourCard/RecommendPreviewFourCard.styles.tsx
  src/components/RecommendPreviewFourCard/RecommendPreviewFourCard.tsx
  src/screens/RecommendScreen/RecommendScreen.header.tsx
  src/screens/RecommendScreen/RecommendScreen.tsx
Labels: feature ✨

#54 [#21] 추천 상세 페이지 구현 및 추천 페이지에서 스크린 이동 기능 구현
  src/TestData.ts
  src/components/FrameRecommendOrganism/FrameRecommendOrganism.tsx
  src/components/PoseRecommendOrganism/PoseRecommendOrganism.tsx
  src/components/RecommendDetailDiffOrganism/RecommendDetailDiffOrganism.styles.tsx
  src/components/RecommendDetailDiffOrganism/RecommendDetailDiffOrganism.tsx
  src/components/RecommendFeedCard/RecommendFeedCard.styles.tsx
  src/components/RecommendFeedCard/RecommendFeedCard.tsx
  src/components/RecommendPreviewFourCard/RecommendPreviewFourCard.tsx
  src/components/utils/Pressables/PressableIcons.tsx
  src/icons/LeftArrowIcon.tsx
  src/screens/RecommendScreen/RecommendDetailScreen.header.tsx
  src/screens/RecommendScreen/RecommendDetailScreen.tsx
  src/screens/RecommendScreen/RecommendScreen.tsx
  src/screens/RecommendScreen/index.tsx
Labels: feature ✨
